"""update scenario table

Revision ID: d19b9dcd3310
Revises: 7556ebc1f312
Create Date: 2023-09-26 01:25:47.547072

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d19b9dcd3310"
down_revision = "7556ebc1f312"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenarios",
        sa.Column(
            "team_id",
            sa.Integer(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scenarios", "team_id")
    # ### end Alembic commands ###
