"""create company_exclude_collections table

Revision ID: 8eb548021b55
Revises: ef95b398af7a
Create Date: 2023-03-06 03:19:54.939593

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8eb548021b55"
down_revision = "ef95b398af7a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_exclude_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("type_code", sa.String(length=20), nullable=True),
        sa.Column("identification_rate", sa.Float(), nullable=True),
        sa.Column("csv_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_exclude_collections")
    # ### end Alembic commands ###
