"""Updated team_companies table

Revision ID: 305edbb29944
Revises: af969e6ab4a1
Create Date: 2023-06-20 09:15:31.516001

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "305edbb29944"
down_revision = "af969e6ab4a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_companies", sa.Column("corporate_number", sa.Text(), nullable=True)
    )
    op.drop_column("team_companies", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_companies",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("team_companies", "corporate_number")
    # ### end Alembic commands ###
