"""update_column_team_id_tracking_urls_table

Revision ID: 878419ef4008
Revises: 728d1000e603
Create Date: 2023-07-20 02:04:55.282967

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "878419ef4008"
down_revision = "728d1000e603"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracking_urls", sa.Column("team_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracking_urls", "team_id")
    # ### end Alembic commands ###
