"""add colunm team id to todo table

Revision ID: fd393c664fbd
Revises: fb1a30a364d5
Create Date: 2023-05-17 10:25:09.966471

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd393c664fbd"
down_revision = "e6c068160c92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("team_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "team_id")

    # ### end Alembic commands ###
