"""add columns to recruit table

Revision ID: e8a706b17f3c
Revises: ce4f8c939a5c
Create Date: 2023-07-04 06:57:40.476070

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8a706b17f3c"
down_revision = "ce4f8c939a5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recruits", sa.Column("sub_title", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("explain", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "recruits",
        sa.Column(
            "employment_type_codes", sa.ARRAY(sa.String(length=20)), nullable=True
        ),
    )
    op.add_column(
        "recruits",
        sa.Column("recruit_tels", sa.ARRAY(sa.String(length=20)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("recruit_mails", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column(
            "working_address_list", sa.ARRAY(sa.String(length=2048)), nullable=True
        ),
    )
    op.add_column("recruits", sa.Column("working_location", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("working_time", sa.Text(), nullable=True))
    op.add_column(
        "recruits", sa.Column("application_contacts", sa.Text(), nullable=True)
    )
    op.add_column("recruits", sa.Column("application_flow", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("recruitment_count", sa.Text(), nullable=True))
    op.add_column(
        "recruits",
        sa.Column("recruit_sales_approach_reject_flag", sa.Boolean(), nullable=True),
    )
    op.add_column("recruits", sa.Column("remote_flag", sa.Boolean(), nullable=True))
    op.add_column(
        "recruits", sa.Column("full_remote_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("required_educational_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("required_college_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "recruits",
        sa.Column("required_university_graduate_flag", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("required_post_graduate_flag", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "recruits", sa.Column("allow_sidejob_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("online_interview_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("attitude_test_flag", sa.Boolean(), nullable=True)
    )
    op.add_column("recruits", sa.Column("salary_year_min", sa.Integer(), nullable=True))
    op.add_column("recruits", sa.Column("salary_year_max", sa.Integer(), nullable=True))
    op.add_column(
        "recruits", sa.Column("salary_year_value", sa.Integer(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("salary_month_min", sa.Integer(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("salary_month_max", sa.Integer(), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("salary_month_value", sa.Integer(), nullable=True)
    )
    op.add_column("recruits", sa.Column("salary_day_min", sa.Integer(), nullable=True))
    op.add_column("recruits", sa.Column("salary_day_max", sa.Integer(), nullable=True))
    op.add_column(
        "recruits", sa.Column("salary_day_value", sa.Integer(), nullable=True)
    )
    op.add_column("recruits", sa.Column("salary_hour_min", sa.Integer(), nullable=True))
    op.add_column("recruits", sa.Column("salary_hour_max", sa.Integer(), nullable=True))
    op.add_column(
        "recruits", sa.Column("salary_hour_value", sa.Integer(), nullable=True)
    )
    op.add_column("recruits", sa.Column("salary_raw", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("welfare_benefit", sa.Text(), nullable=True))
    op.add_column("recruits", sa.Column("holiday", sa.Text(), nullable=True))
    op.add_column(
        "recruits",
        sa.Column(
            "recruit_qualifications", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "recruits",
        sa.Column("tech_languages", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("tech_frameworks", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("tech_clouds", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("tech_databases", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column(
            "communication_tools", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "recruits",
        sa.Column("management_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("internal_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("crm_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("skill_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("search_keywords", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "recruits", sa.Column("large_category", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("medium_category", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("small_category", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("job_company_id", sa.String(length=255), nullable=True)
    )
    op.add_column("recruits", sa.Column("other_info", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "recruits_unique_key", "recruits", ["media_code", "media_internal_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recruits_unique_key", "recruits", type_="unique")
    op.drop_column("recruits", "other_info")
    op.drop_column("recruits", "job_company_id")
    op.drop_column("recruits", "small_category")
    op.drop_column("recruits", "medium_category")
    op.drop_column("recruits", "large_category")
    op.drop_column("recruits", "search_keywords")
    op.drop_column("recruits", "skill_codes")
    op.drop_column("recruits", "crm_tools")
    op.drop_column("recruits", "internal_tools")
    op.drop_column("recruits", "management_tools")
    op.drop_column("recruits", "communication_tools")
    op.drop_column("recruits", "tech_databases")
    op.drop_column("recruits", "tech_clouds")
    op.drop_column("recruits", "tech_frameworks")
    op.drop_column("recruits", "tech_languages")
    op.drop_column("recruits", "recruit_qualifications")
    op.drop_column("recruits", "holiday")
    op.drop_column("recruits", "welfare_benefit")
    op.drop_column("recruits", "salary_raw")
    op.drop_column("recruits", "salary_hour_value")
    op.drop_column("recruits", "salary_hour_max")
    op.drop_column("recruits", "salary_hour_min")
    op.drop_column("recruits", "salary_day_value")
    op.drop_column("recruits", "salary_day_max")
    op.drop_column("recruits", "salary_day_min")
    op.drop_column("recruits", "salary_month_value")
    op.drop_column("recruits", "salary_month_max")
    op.drop_column("recruits", "salary_month_min")
    op.drop_column("recruits", "salary_year_value")
    op.drop_column("recruits", "salary_year_max")
    op.drop_column("recruits", "salary_year_min")
    op.drop_column("recruits", "attitude_test_flag")
    op.drop_column("recruits", "online_interview_flag")
    op.drop_column("recruits", "allow_sidejob_flag")
    op.drop_column("recruits", "required_post_graduate_flag")
    op.drop_column("recruits", "required_university_graduate_flag")
    op.drop_column("recruits", "required_college_flag")
    op.drop_column("recruits", "required_educational_flag")
    op.drop_column("recruits", "full_remote_flag")
    op.drop_column("recruits", "remote_flag")
    op.drop_column("recruits", "recruit_sales_approach_reject_flag")
    op.drop_column("recruits", "recruitment_count")
    op.drop_column("recruits", "application_flow")
    op.drop_column("recruits", "application_contacts")
    op.drop_column("recruits", "working_time")
    op.drop_column("recruits", "working_location")
    op.drop_column("recruits", "working_address_list")
    op.drop_column("recruits", "recruit_mails")
    op.drop_column("recruits", "recruit_tels")
    op.drop_column("recruits", "employment_type_codes")
    op.drop_column("recruits", "summary")
    op.drop_column("recruits", "explain")
    op.drop_column("recruits", "sub_title")
    # ### end Alembic commands ###
