"""Update press_releases table

Revision ID: d259f4602569
Revises: 037a746c9ddc
Create Date: 2023-06-16 08:19:40.910897

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d259f4602569"
down_revision = "037a746c9ddc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "press_releases", "coporate_number", new_column_name="corporate_number"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "press_releases", "corporate_number", new_column_name="coporate_number"
    )
    # ### end Alembic commands ###
