"""Updated companies table

Revision ID: cd64b820a55a
Revises: 1e6967241c6d
Create Date: 2023-06-07 10:41:34.073235

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cd64b820a55a"
down_revision = "1e6967241c6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("main_sub_industry_code", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "sub_industries_code", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column("companies", sa.Column("revenue_raw", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("capital_raw", sa.Text(), nullable=True))
    op.add_column(
        "companies",
        sa.Column("tool_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("one_month_employee_delta", sa.Integer(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("three_month_employee_delta", sa.Integer(), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("six_month_employee_delta", sa.Integer(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("one_year_employee_delta", sa.Integer(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("one_month_capital_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("three_month_capital_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("six_month_capital_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("one_year_capital_delta", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("one_month_revenue_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("three_month_revenue_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("six_month_revenue_delta", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("one_year_revenue_delta", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("latest_new_graduate_recruit_at", sa.BigInteger(), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("occupation_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("raw_occupations", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("skill_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies", sa.Column("group_employee_count", sa.Integer(), nullable=True)
    )
    op.add_column("companies", sa.Column("main_customers", sa.Text(), nullable=True))
    op.add_column("companies", sa.Column("group_companies", sa.Text(), nullable=True))
    op.add_column(
        "companies", sa.Column("market_capitalization_raw", sa.Text(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("market_capitalization", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("address_latitude", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("address_longitude", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("recruit_tags", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "recruit_qualifications", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column("tech_languages", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("tech_frameworks", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("tech_clouds", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("tech_databases", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column(
            "communication_tools", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column("management_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("internal_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "companies",
        sa.Column("crm_tools", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "crm_tools")
    op.drop_column("companies", "internal_tools")
    op.drop_column("companies", "management_tools")
    op.drop_column("companies", "communication_tools")
    op.drop_column("companies", "tech_databases")
    op.drop_column("companies", "tech_clouds")
    op.drop_column("companies", "tech_frameworks")
    op.drop_column("companies", "tech_languages")
    op.drop_column("companies", "recruit_qualifications")
    op.drop_column("companies", "recruit_tags")
    op.drop_column("companies", "address_longitude")
    op.drop_column("companies", "address_latitude")
    op.drop_column("companies", "market_capitalization")
    op.drop_column("companies", "market_capitalization_raw")
    op.drop_column("companies", "group_companies")
    op.drop_column("companies", "main_customers")
    op.drop_column("companies", "group_employee_count")
    op.drop_column("companies", "skill_codes")
    op.drop_column("companies", "raw_occupations")
    op.drop_column("companies", "occupation_codes")
    op.drop_column("companies", "latest_new_graduate_recruit_at")
    op.drop_column("companies", "one_year_revenue_delta")
    op.drop_column("companies", "six_month_revenue_delta")
    op.drop_column("companies", "three_month_revenue_delta")
    op.drop_column("companies", "one_month_revenue_delta")
    op.drop_column("companies", "one_year_capital_delta")
    op.drop_column("companies", "six_month_capital_delta")
    op.drop_column("companies", "three_month_capital_delta")
    op.drop_column("companies", "one_month_capital_delta")
    op.drop_column("companies", "one_year_employee_delta")
    op.drop_column("companies", "six_month_employee_delta")
    op.drop_column("companies", "three_month_employee_delta")
    op.drop_column("companies", "one_month_employee_delta")
    op.drop_column("companies", "tool_codes")
    op.drop_column("companies", "capital_raw")
    op.drop_column("companies", "revenue_raw")
    op.drop_column("companies", "sub_industries_code")
    op.drop_column("companies", "main_sub_industry_code")
    # ### end Alembic commands ###
