"""Added scenarios table

Revision ID: 7556ebc1f312
Revises: ec099eef7421
Create Date: 2023-09-22 10:31:18.767123

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7556ebc1f312"
down_revision = "ec099eef7421"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenarios",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("trigger_conditions", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_emails", sa.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("target_slack_connection_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenarios")
    # ### end Alembic commands ###
