"""create companies table

Revision ID: 79d4c0dc5b91
Revises: c1db6bcc6912
Create Date: 2023-03-03 08:26:38.123876

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "79d4c0dc5b91"
down_revision = "c1db6bcc6912"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("estabilish_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kana_name", sa.TEXT(), nullable=True),
        sa.Column("english_name", sa.TEXT(), nullable=True),
        sa.Column("postal_code", sa.Integer(), nullable=True),
        sa.Column("nta_city_id", sa.Integer(), nullable=True),
        sa.Column("nta_prefecture_id", sa.Integer(), nullable=True),
        sa.Column("corporate_number", sa.TEXT(), nullable=True),
        sa.Column("corporate_kind", sa.SmallInteger(), nullable=True),
        sa.Column("nta_closed_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("nta_closed_reason", sa.TEXT(), nullable=True),
        sa.Column("nta_updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("nta_created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("president_name", sa.TEXT(), nullable=True),
        sa.Column("president_dob", sa.TIMESTAMP(), nullable=True),
        sa.Column("factories_count", sa.Integer(), nullable=True),
        sa.Column("branches_count", sa.Integer(), nullable=True),
        sa.Column("headquarters_count", sa.Integer(), nullable=True),
        sa.Column("industry_id", sa.Integer(), nullable=True),
        sa.Column("business_content", sa.TEXT(), nullable=True),
        sa.Column("listing_market_id", sa.SmallInteger(), nullable=True),
        sa.Column("listing_year", sa.Integer(), nullable=True),
        sa.Column("revenue_change", sa.Integer(), nullable=True),
        sa.Column("employee_change", sa.Integer(), nullable=True),
        sa.Column("revenue_change_rate", sa.Float(), nullable=True),
        sa.Column("youtube_url", sa.TEXT(), nullable=True),
        sa.Column("twitter_url", sa.TEXT(), nullable=True),
        sa.Column("facebook_url", sa.TEXT(), nullable=True),
        sa.Column("contact_form_url", sa.TEXT(), nullable=True),
        sa.Column("president_university", sa.TEXT(), nullable=True),
        sa.Column("revenue", sa.Integer(), nullable=True),
        sa.Column("recruit_phone", sa.TEXT(), nullable=True),
        sa.Column("sub_companies_count", sa.Integer(), nullable=True),
        sa.Column("phone", sa.TEXT(), nullable=True),
        sa.Column("recruit_email", sa.TEXT(), nullable=True),
        sa.Column("contact_email", sa.TEXT(), nullable=True),
        sa.Column("capital_adequacy_ratio", sa.Float(), nullable=True),
        sa.Column("capital", sa.Integer(), nullable=True),
        sa.Column("capital_change", sa.Integer(), nullable=True),
        sa.Column("average_work_duration", sa.Float(), nullable=True),
        sa.Column("fax", sa.TEXT(), nullable=True),
        sa.Column("closing_month", sa.SmallInteger(), nullable=True),
        sa.Column("employee_change_rate", sa.Float(), nullable=True),
        sa.Column("employees_count", sa.Integer(), nullable=True),
        sa.Column("average_age", sa.Float(), nullable=True),
        sa.Column("average_salary", sa.Integer(), nullable=True),
        sa.Column("latest_recruits_at", sa.Integer(), nullable=True),
        sa.Column("this_month_recruits_count", sa.Integer(), nullable=True),
        sa.Column(
            "this_month_mynavi_tenshoku_recruits_count", sa.Integer(), nullable=True
        ),
        sa.Column("latest_press_release_at", sa.Integer(), nullable=True),
        sa.Column("this_month_prtimes_count", sa.Integer(), nullable=True),
        sa.Column("this_month_value_press_count", sa.Integer(), nullable=True),
        sa.Column("display_flag", sa.SmallInteger(), nullable=True),
        sa.Column("meta_title", sa.TEXT(), nullable=True),
        sa.Column("meta_description", sa.TEXT(), nullable=True),
        sa.Column("meta_keywords", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column(
            "establish_time_level", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("hp_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "listing_time_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companies")
    # ### end Alembic commands ###
