"""update teams table

Revision ID: a23e72debc8a
Revises: 6349a7fc6b66
Create Date: 2023-07-21 04:12:31.796522

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a23e72debc8a"
down_revision = "6349a7fc6b66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("teams", "plan_code", new_column_name="listing_plan_code")
    op.add_column(
        "teams",
        sa.Column(
            "form_plan_code",
            sa.Enum("PRE", "ADV", "STD", "SML", "FRE", name="plancode"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "form_plan_code")
    op.alter_column("teams", "listing_plan_code", new_column_name="plan_code")
    # ### end Alembic commands ###
