"""update form_job_items table

Revision ID: b0b0609fe1b4
Revises: c6315798eb6b
Create Date: 2023-07-19 06:19:14.558453

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0b0609fe1b4"
down_revision = "c6315798eb6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_job_items",
        sa.Column("aws_batch_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_job_items", "aws_batch_id")
    # ### end Alembic commands ###
