"""update_persons_table

Revision ID: a66b1e284736
Revises: 1290c2d96595
Create Date: 2023-07-25 07:42:34.286274

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a66b1e284736"
down_revision = "1290c2d96595"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons", sa.Column("corporate_number", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "persons", sa.Column("wantedly_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "persons",
        sa.Column("linkedin_internal_id", sa.String(length=255), nullable=True),
    )
    op.add_column("persons", sa.Column("address", sa.Text(), nullable=True))
    op.drop_column("persons", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("persons", "corporate_number")
    op.drop_column("persons", "wantedly_id")
    op.drop_column("persons", "linkedin_internal_id")
    op.drop_column("persons", "address")
    # ### end Alembic commands ###
