"""updated team_companies table

Revision ID: 0ea6e027953a
Revises: fb1a30a364d5
Create Date: 2023-05-17 08:03:12.644870

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0ea6e027953a"
down_revision = "fb1a30a364d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_companies",
        sa.Column("tags", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_companies", "tags")
    # ### end Alembic commands ###
