"""update person add bio column

Revision ID: 594317411a80
Revises: 2c754dfbd506
Create Date: 2023-09-13 01:58:57.908642

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "594317411a80"
down_revision = "2c754dfbd506"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("bio", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "bio")
    # ### end Alembic commands ###
