"""create person_collections table

Revision ID: 43b762659356
Revises: d73db214b529
Create Date: 2023-03-06 04:27:52.053563

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "43b762659356"
down_revision = "d73db214b529"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status_code", sa.String(length=20), nullable=True),
        sa.Column("search_condition", sa.JSON(), nullable=True),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("type_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_collections")
    # ### end Alembic commands ###
