"""create form_jobs table

Revision ID: c94046fe7950
Revises: 24ab22012ffc
Create Date: 2023-03-03 08:28:46.690304

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c94046fe7950"
down_revision = "24ab22012ffc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_jobs",
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("target_collection_id", sa.Integer(), nullable=True),
        sa.Column("exclude_collection_id", sa.Integer(), nullable=True),
        sa.Column("approach_ng_flag", sa.Integer(), nullable=True),
        sa.Column("schedule_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("max_resend_code", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_jobs")
    # ### end Alembic commands ###
