"""Update form_job_items table

Revision ID: 9b5541bc4ea6
Revises: 2c5689a7f522
Create Date: 2023-06-21 07:46:55.512397

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b5541bc4ea6"
down_revision = "2c5689a7f522"
branch_labels = None
depends_on = None

status_code = postgresql.ENUM(
    "PENDING", "QUEUED", "SUCCESS", "ERROR", name="form_job_item_status_code"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_code.create(op.get_bind())
    op.alter_column(
        "form_job_items",
        "company_id",
        new_column_name="corporate_number",
        type_=sa.String(255),
    )
    op.alter_column(
        "form_job_items",
        "status_code",
        type_=status_code,
        postgresql_using="status_code::form_job_item_status_code",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "form_job_items",
        "corporate_number",
        new_column_name="company_id",
        type_=sa.Integer(),
    )
    op.alter_column("form_job_items", "status_code", type_=sa.String(20))
    status_code.drop(op.get_bind())
    # ### end Alembic commands ###
