"""Update plans table

Revision ID: ba51a9b29821
Revises: d46e93a7063e
Create Date: 2023-07-12 10:41:10.324009

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ba51a9b29821"
down_revision = "d46e93a7063e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plans", sa.Column("name_code", sa.String(length=20), nullable=True))
    op.add_column("plans", sa.Column("download_cpn_quota", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("ctf_quota", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "ctf_quota")
    op.drop_column("plans", "download_cpn_quota")
    op.drop_column("plans", "name_code")
    # ### end Alembic commands ###
