"""Add_column_coporate_number_to_press_release_table

Revision ID: 1e6967241c6d
Revises: 2a9251b894db
Create Date: 2023-06-05 07:35:04.829559

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e6967241c6d"
down_revision = "2a9251b894db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "press_releases", sa.Column("coporate_number", sa.String(20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("press_releases", "coporate_number")
    # ### end Alembic commands ###
