"""add columns to press_release

Revision ID: b8c2a644c3b8
Revises: ce4f8c939a5c
Create Date: 2023-06-29 01:41:52.344719

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ce4f8c939a5c"
down_revision = ("30757c2b4362", "edb2515baae7")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "press_releases",
        sa.Column("media_internal_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "press_releases", sa.Column("type_code", sa.String(length=20), nullable=True)
    )
    op.add_column("press_releases", sa.Column("sub_title", sa.Text(), nullable=True))
    op.add_column(
        "press_releases",
        sa.Column("body_urls", sa.ARRAY(sa.String(length=2048)), nullable=True),
    )
    op.add_column(
        "press_releases",
        sa.Column(
            "business_category_texts", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "press_releases",
        sa.Column(
            "business_category_urls", sa.ARRAY(sa.String(length=2048)), nullable=True
        ),
    )
    op.add_column(
        "press_releases",
        sa.Column(
            "prtimes_location_info_texts",
            sa.ARRAY(sa.String(length=255)),
            nullable=True,
        ),
    )
    op.add_column(
        "press_releases",
        sa.Column(
            "prtimes_location_info_urls",
            sa.ARRAY(sa.String(length=2048)),
            nullable=True,
        ),
    )
    op.add_column(
        "press_releases",
        sa.Column("keyword_texts", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    op.add_column(
        "press_releases",
        sa.Column("keyword_urls", sa.ARRAY(sa.String(length=2048)), nullable=True),
    )
    op.add_column(
        "press_releases",
        sa.Column("posted_at_raw", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "press_releases", sa.Column("posted_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "press_releases",
        sa.Column("article_company_id", sa.String(length=30), nullable=True),
    )
    op.create_unique_constraint(
        "articles_unique_id", "press_releases", ["media_code", "media_internal_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("articles_unique_id", "press_releases", type_="unique")
    op.drop_column("press_releases", "article_company_id")
    op.drop_column("press_releases", "posted_at")
    op.drop_column("press_releases", "posted_at_raw")
    op.drop_column("press_releases", "keyword_urls")
    op.drop_column("press_releases", "keyword_texts")
    op.drop_column("press_releases", "prtimes_location_info_urls")
    op.drop_column("press_releases", "prtimes_location_info_texts")
    op.drop_column("press_releases", "business_category_urls")
    op.drop_column("press_releases", "business_category_texts")
    op.drop_column("press_releases", "body_urls")
    op.drop_column("press_releases", "sub_title")
    op.drop_column("press_releases", "type_code")
    op.drop_column("press_releases", "media_internal_id")
    # ### end Alembic commands ###
