"""add team id column to mail templates table

Revision ID: 4ada74ac1714
Revises: 6ba6e0c5dcf9
Create Date: 2023-11-23 08:08:28.069609

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4ada74ac1714"
down_revision = "6ba6e0c5dcf9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mail_templates", sa.Column("team_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mail_templates", "team_id")
    # ### end Alembic commands ###
