"""Added company_collection_items table

Revision ID: 037a746c9ddc
Revises: fafb87f21679
Create Date: 2023-06-13 11:29:18.067605

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "037a746c9ddc"
down_revision = "fafb87f21679"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_collection_items",
        sa.Column("corporate_number", sa.Text(), nullable=True),
    )
    op.drop_column("company_collection_items", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_collection_items",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("company_collection_items", "corporate_number")
    # ### end Alembic commands ###
