"""Added column users table

Revision ID: 2fdd899e06a0
Revises: 305edbb29944
Create Date: 2023-06-21 07:33:20.588548

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2fdd899e06a0"
down_revision = "305edbb29944"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("company_name", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users", sa.Column("department_name", sa.String(length=255), nullable=True)
    )
    op.add_column("users", sa.Column("tel", sa.String(length=20), nullable=True))
    op.add_column(
        "users", sa.Column("expect_meeting_flag", sa.SmallInteger(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("position_code", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "expect_meeting_flag")
    op.drop_column("users", "tel")
    op.drop_column("users", "department_name")
    op.drop_column("users", "company_name")
    op.drop_column("users", "position_code")

    # ### end Alembic commands ###
