"""Updated index companies table

Revision ID: 0cda5e088eab
Revises: 83504171c7e7
Create Date: 2023-07-12 03:45:17.752409

"""


from alembic import op

# revision identifiers, used by Alembic.
revision = "0cda5e088eab"
down_revision = "83504171c7e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_companies_name", "companies", ["name"])
    op.create_index("idx_companies_phone", "companies", ["phone"])
    op.create_index("idx_companies_domain", "companies", ["domain"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_companies_name")
    op.drop_index("idx_companies_phone")
    op.drop_index("idx_companies_domain")
    # ### end Alembic commands ###
