"""update users table

Revision ID: 6cb02015eb2d
Revises: 7b7a30a15073
Create Date: 2023-04-10 10:17:51.610329

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6cb02015eb2d"
down_revision = "7b7a30a15073"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_verified_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified_at")
    # ### end Alembic commands ###
