"""create click_history table

Revision ID: 2cbae428812b
Revises: 0cadf4d3373d
Create Date: 2023-03-06 06:10:51.871741

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2cbae428812b"
down_revision = "0cadf4d3373d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "click_histories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clickable_code", sa.String(length=20), nullable=True),
        sa.Column("clickable_id", sa.Integer(), nullable=True),
        sa.Column("tracking_url_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("click_histories")
    # ### end Alembic commands ###
