"""create mail job items table

Revision ID: 678f8a933b89
Revises: 711903c8ddf5
Create Date: 2023-11-22 03:47:45.735849

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "678f8a933b89"
down_revision = "711903c8ddf5"
branch_labels = None
depends_on = None

status_code = postgresql.ENUM(
    "PENDING", "QUEUED", "RUNNING", "SUCCESS", "ERROR", name="mail_job_item_status_code"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_job_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("aws_batch_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("corporate_number", sa.String(255), nullable=True),
        sa.Column("contact_email", sa.TEXT(), nullable=True),
        sa.Column("status_code", status_code, nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("ended_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mail_job_items")
    # ### end Alembic commands ###
