"""create team_credits table

Revision ID: 6c9d44e403b2
Revises: 8b34651f1d99
Create Date: 2023-04-25 07:44:55.222408

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6c9d44e403b2"
down_revision = "8b34651f1d99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_credits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "reason_code",
            sa.Enum("MONTHLY", "COMPENSATE", "EXCHANGED", name="reasoncode"),
            nullable=True,
        ),
        sa.Column(
            "service_code",
            sa.Enum("CPN", "PERSON", "MSG", name="servicecode"),
            nullable=True,
        ),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("remarks", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_credits")
    op.execute("DROP TYPE servicecode")
    op.execute("DROP TYPE reasoncode")
    # ### end Alembic commands ###
