"""create tracking_urls table

Revision ID: c5fcbf2d5267
Revises: 49db7eea1907
Create Date: 2023-03-06 06:42:26.652474

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c5fcbf2d5267"
down_revision = "49db7eea1907"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.Column("original_url", sa.String(length=1024), nullable=True),
        sa.Column("shorten_path", sa.String(length=1024), nullable=True),
        sa.Column("tracking_flag", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracking_urls")
    # ### end Alembic commands ###
