"""upadte corporate number exclude item

Revision ID: aff8284f494d
Revises: ce4f8c939a5c
Create Date: 2023-07-05 04:05:16.386831

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aff8284f494d"
down_revision = "ce4f8c939a5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "company_exclude_collection_items",
        sa.Column("corporate_number", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "company_exclude_collections",
        sa.Column("description", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_exclude_collections", "description")
    op.drop_column("company_exclude_collection_items", "corporate_number")
    # ### end Alembic commands ###
