"""Updated team_credits table

Revision ID: 8bccf824982b
Revises: d428358be32a
Create Date: 2023-06-22 07:53:14.860650

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bccf824982b"
down_revision = "d428358be32a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE servicecode ADD VALUE 'CTF'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_credits",
        "service_code",
        existing_type=sa.Enum("CPN", "PERSON", "MSG", name="servicecode"),
        nullable=True,
    )
    # ### end Alembic commands ###
