"""create placeholders table

Revision ID: 03509eb2ed3a
Revises: 617a19a511f4
Create Date: 2023-03-03 08:32:43.028336

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "03509eb2ed3a"
down_revision = "617a19a511f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "placeholders",
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=1024), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("placeholders")
    # ### end Alembic commands ###
