"""Updated companies table

Revision ID: fafb87f21679
Revises: cd64b820a55a
Create Date: 2023-06-12 03:58:00.382712

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fafb87f21679"
down_revision = "cd64b820a55a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("press_release_media_codes", sa.String(length=255), nullable=True),
    )
    op.drop_column("companies", "latest_recruits_at")
    op.drop_column("companies", "latest_new_graduate_recruit_at")
    op.add_column(
        "companies", sa.Column("latest_recruits_at", sa.TIMESTAMP, nullable=True)
    )
    op.add_column(
        "companies",
        sa.Column("latest_new_graduate_recruit_at", sa.TIMESTAMP, nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "press_release_media_codes")
    op.drop_column("companies", "latest_recruits_at")
    op.drop_column("companies", "latest_new_graduate_recruit_at")
    # ### end Alembic commands ###
