"""update_corporate_number_activity_logs_table

Revision ID: f1d9b277c701
Revises: 305edbb29944
Create Date: 2023-06-21 09:52:00.370041

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f1d9b277c701"
down_revision = "305edbb29944"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_logs", sa.Column("corporate_number", sa.Text(), nullable=True)
    )
    op.drop_column("activity_logs", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activity_logs",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("activity_logs", "corporate_number")
    # ### end Alembic commands ###
