"""update_column_recruits_table

Revision ID: 30757c2b4362
Revises: 8bccf824982b
Create Date: 2023-06-23 09:05:49.223086

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "30757c2b4362"
down_revision = "8bccf824982b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruits", sa.Column("corporate_number", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "recruits", sa.Column("media_internal_id", sa.String(length=256), nullable=True)
    )
    op.drop_column("recruits", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruits",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("recruits", "media_internal_id")
    op.drop_column("recruits", "corporate_number")

    # ### end Alembic commands ###
