"""Updated downloaded_histories table

Revision ID: b31af63368c5
Revises: 8a3af854f452
Create Date: 2023-09-08 07:25:05.457047

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b31af63368c5"
down_revision = "8a3af854f452"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "downloaded_histories",
        sa.Column(
            "service_code",
            sa.Enum("CPN", "PERSON", name="servicecode"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("downloaded_histories", "service_code")
    # ### end Alembic commands ###
