"""create_scenario_notification_items

Revision ID: af0b2e82c438
Revises: f47ff24f463b
Create Date: 2023-10-04 02:48:10.593238

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "af0b2e82c438"
down_revision = "f47ff24f463b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario_notification_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scenario_notification_id", sa.Integer(), nullable=False),
        sa.Column("recruit_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_notification_items")
    # ### end Alembic commands ###
