"""add columns to company

Revision ID: edb2515baae7
Revises: 8bccf824982b
Create Date: 2023-06-26 01:16:51.232404

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "edb2515baae7"
down_revision = "8bccf824982b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "business_model_codes", sa.ARRAY(sa.String(length=10)), nullable=True
        ),
    )
    op.add_column(
        "companies", sa.Column("display_ng_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("contact_ng_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("contact_info_ng_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "companies", sa.Column("contact_sales_ng_flag", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "contact_sales_ng_flag")
    op.drop_column("companies", "contact_info_ng_flag")
    op.drop_column("companies", "contact_ng_flag")
    op.drop_column("companies", "display_ng_flag")
    op.drop_column("companies", "business_model_codes")
    # ### end Alembic commands ###
