"""create company_collections table

Revision ID: e7a206857f47
Revises: ca1f3a07447d
Create Date: 2023-03-06 03:09:52.313031

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e7a206857f47"
down_revision = "ca1f3a07447d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("status_code", sa.String(length=20), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("step", sa.Integer(), nullable=True),
        sa.Column("type_code", sa.String(length=255), nullable=True),
        sa.Column("csv_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_collections")
    # ### end Alembic commands ###
