"""Added columns table person_colections

Revision ID: 37741c1f9723
Revises: 7c80d0573d4e
Create Date: 2023-07-25 02:08:24.971857

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "37741c1f9723"
down_revision = "8d78ec8a156a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person_collections",
        sa.Column("tags", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person_collections", "tags")
    # ### end Alembic commands ###
