"""comment

Revision ID: 450c2bfac22f
Revises: c51114b3fb99
Create Date: 2023-10-26 12:40:34.037338

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "450c2bfac22f"
down_revision = "c51114b3fb99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "company_collections",
        sa.Column("mode_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_collections", "mode_code")
    # ### end Alembic commands ###
