"""create message_jobs table

Revision ID: 019d6aa2cc26
Revises: ceb35ed1c7a4
Create Date: 2023-03-06 04:50:51.583377

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "019d6aa2cc26"
down_revision = "ceb35ed1c7a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("platform_code", sa.String(length=255), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("exclude_keyman_collection_id", sa.Integer(), nullable=True),
        sa.Column("schedule_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("connection_only_flag", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_jobs")
    # ### end Alembic commands ###
