"""add name to prefecture and city table

Revision ID: af1c2d1080d4
Revises: 2a9251b894db
Create Date: 2023-06-02 07:31:38.664292

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a9251b894db"
down_revision = ("1f41fdc468dc", "29799b1c0315")
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cities", sa.Column("name", sa.String(length=50), nullable=True))
    op.add_column("cities", sa.Column("prefecture_id", sa.Integer(), nullable=True))
    op.add_column("prefectures", sa.Column("name", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prefectures", "name")
    op.drop_column("cities", "prefecture_id")
    op.drop_column("cities", "name")
    # ### end Alembic commands ###
