"""Add job id to form_job_items table

Revision ID: 1f41fdc468dc
Revises: 1411d0fc0928
Create Date: 2023-05-30 01:51:39.532181

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f41fdc468dc"
down_revision = "1411d0fc0928"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_job_items", sa.Column("job_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_job_items", "job_id")
    # ### end Alembic commands ###
