"""Update placeholder_items table

Revision ID: 46c15b58c1e9
Revises: 037a746c9ddc
Create Date: 2023-06-15 02:41:36.792035

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "46c15b58c1e9"
down_revision = "d259f4602569"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("placeholders_items", "placeholder_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("placeholder_items", "placeholders_items")
    # ### end Alembic commands ###
