"""update plans table

Revision ID: 7fed9f28dd5f
Revises: a23e72debc8a
Create Date: 2023-07-21 04:13:56.664161

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7fed9f28dd5f"
down_revision = "a23e72debc8a"
branch_labels = None
depends_on = None


plan_service_code = postgresql.ENUM(
    "LISTING",
    "FORM",
    name="plan_service_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    plan_service_code.create(op.get_bind())
    op.add_column(
        "plans",
        sa.Column(
            "service_code",
            plan_service_code,
            nullable=True,
        ),
    )
    op.add_column(
        "subcriptions",
        sa.Column(
            "service_code",
            plan_service_code,
            nullable=True,
        ),
    )
    op.execute(
        "ALTER TABLE plans ALTER COLUMN "
        "name_code TYPE plancode"
        " USING name_code::text::plancode"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("plans", "service_code")
    op.drop_column("subcriptions", "service_code")
    plan_service_code.drop(op.get_bind())
    op.execute(
        "ALTER TABLE plans ALTER COLUMN name_code "
        "TYPE varchar(20) USING name_code::varchar"
    )
    # ### end Alembic commands ###
