"""update colunm model code activity log table

Revision ID: efec2cb433fb
Revises: fd393c664fbd
Create Date: 2023-05-18 07:09:44.390533

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "efec2cb433fb"
down_revision = "fd393c664fbd"
branch_labels = None
depends_on = None

model_code = postgresql.ENUM(
    "TODO",
    "FORM",
    "MAIL",
    name="model_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    model_code.create(op.get_bind())
    op.alter_column(
        "activity_logs",
        "model_code",
        existing_type=sa.String(length=20),
        type_=model_code,
        nullable=True,
        postgresql_using="model_code::model_code",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "activity_logs",
        "model_code",
        existing_type=model_code,
        type_=sa.String(length=20),
        nullable=True,
        postgresql_using="model_code::model_code",
    )
    model_code.drop(op.get_bind())
    # ### end Alembic commands ###
