"""update_column_corporate_text_to_varchar

Revision ID: d428358be32a
Revises: ee0e3d1c62c4
Create Date: 2023-06-22 02:06:40.973401

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d428358be32a"
down_revision = "ee0e3d1c62c4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "todos",
        "corporate_number",
        type_=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "activity_logs",
        "corporate_number",
        type_=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "todos",
        "corporate_number",
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "activity_logs",
        "corporate_number",
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###
