"""Update companies table

Revision ID: e843c86d5d44
Revises: 49bd565e436e
Create Date: 2023-05-26 03:52:44.835733

"""

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e843c86d5d44"
down_revision = "49bd565e436e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "industry_id",
        new_column_name="industry_code",
        type_=postgresql.VARCHAR(255),
    )
    op.alter_column(
        "companies",
        "listing_market_id",
        new_column_name="listing_market_code",
        type_=postgresql.VARCHAR(255),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "listing_market_code",
        new_column_name="listing_market_id",
        type_=postgresql.INTEGER,
    )
    op.alter_column(
        "companies",
        "industry_code",
        new_column_name="industry_id",
        type_=postgresql.INTEGER,
    )
    # ### end Alembic commands ###
