"""Add placeholder_id to form_jobs table

Revision ID: 1411d0fc0928
Revises: 69e0aead30d4
Create Date: 2023-05-26 07:03:07.365519

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1411d0fc0928"
down_revision = "69e0aead30d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_jobs", "group_id", new_column_name="placeholder_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("form_jobs", "placeholder_id", new_column_name="group_id")
    # ### end Alembic commands ###
