"""update teams table

Revision ID: 8b34651f1d99
Revises: 79c10bcd1d63
Create Date: 2023-04-25 07:32:50.512720

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8b34651f1d99"
down_revision = "79c10bcd1d63"
branch_labels = None
depends_on = None

plan_code = postgresql.ENUM("PRE", "ADV", "STD", "SML", name="plancode")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    plan_code.create(op.get_bind())
    op.add_column(
        "teams",
        sa.Column(
            "plan_code",
            plan_code,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "plan_code")
    plan_code.drop(op.get_bind())
    # ### end Alembic commands ###
