"""updated status_code for team_companies table

Revision ID: e6c068160c92
Revises: 0ea6e027953a
Create Date: 2023-05-17 08:30:40.768016

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e6c068160c92"
down_revision = "0ea6e027953a"
branch_labels = None
depends_on = None

status_code = postgresql.ENUM(
    "PENDING",
    "APPROACH_NG",
    "APO_WON",
    "APO_EXPECTED",
    "RECALL",
    name="status_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_code.create(op.get_bind())
    op.alter_column(
        "team_companies",
        "status_code",
        existing_type=sa.String(length=20),
        type_=status_code,
        nullable=True,
        postgresql_using="status_code::status_code",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_companies",
        "status_code",
        existing_type=status_code,
        type_=sa.String(length=20),
        nullable=True,
        postgresql_using="status_code::status_code",
    )
    status_code.drop(op.get_bind())
    # ### end Alembic commands ###
