"""create_wantedly_person_educations_table

Revision ID: 2409552e5d35
Revises: ecc6c8dbe689
Create Date: 2023-08-15 06:07:03.122473

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2409552e5d35"
down_revision = "ecc6c8dbe689"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wantedly_person_educations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person_uuid", sa.String(length=64), nullable=True),
        sa.Column("school_name", sa.String(length=255), nullable=True),
        sa.Column("role_code", sa.String(length=20), nullable=True),
        sa.Column("role_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("start_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("end_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wantedly_person_educations")
    # ### end Alembic commands ###
