"""Added column subscriptions table

Revision ID: 5352cec01e62
Revises: 2fdd899e06a0
Create Date: 2023-06-21 09:09:26.097600

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5352cec01e62"
down_revision = "2fdd899e06a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "subcriptions", sa.Column("plan_code", sa.String(length=20), nullable=True)
    )
    op.add_column("subcriptions", sa.Column("expire_at", sa.TIMESTAMP(), nullable=True))
    op.drop_column("subcriptions", "plan_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subcriptions",
        sa.Column("plan_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("subcriptions", "expire_at")
    op.drop_column("subcriptions", "plan_code")
    # ### end Alembic commands ###
