"""Update form_job_table

Revision ID: 2c5689a7f522
Revises: 305edbb29944
Create Date: 2023-06-21 07:18:45.933873

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2c5689a7f522"
down_revision = "305edbb29944"
branch_labels = None
depends_on = None

status_code = postgresql.ENUM(
    "PENDING",
    "QUEUED",
    "RUNNING_SUCCESS",
    "RUNIING_ERROR",
    "DONE_SUCCESS",
    "DONE_ERROR",
    name="form_job_status_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_code.create(op.get_bind())
    op.add_column(
        "form_jobs",
        sa.Column(
            "status_code",
            status_code,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_jobs", "status_code")
    status_code.drop(op.get_bind())
    # ### end Alembic commands ###
