"""Update team_companies table

Revision ID: af969e6ab4a1
Revises: 46c15b58c1e9
Create Date: 2023-06-16 04:43:36.732698

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "af969e6ab4a1"
down_revision = "46c15b58c1e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_companies",
        sa.Column("sent_contact_form_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_companies", "sent_contact_form_count")
    # ### end Alembic commands ###
