"""update_corporate_number_todos_table

Revision ID: 41fdab909697
Revises: f1d9b277c701
Create Date: 2023-06-21 10:54:41.075665

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "41fdab909697"
down_revision = "f1d9b277c701"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("corporate_number", sa.Text(), nullable=True))
    op.drop_column("todos", "company_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos",
        sa.Column("company_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("todos", "corporate_number")
    # ### end Alembic commands ###
