"""Add colunm team id form template table

Revision ID: f8a55e487ab1
Revises: efec2cb433fb
Create Date: 2023-05-18 07:44:30.171467

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f8a55e487ab1"
down_revision = "efec2cb433fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_templates", sa.Column("team_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_templates", "team_id")
    # ### end Alembic commands ###
