"""update form_job_items table

Revision ID: 29776c198ae3
Revises: d0eefbc4667a
Create Date: 2023-07-26 10:12:09.389157

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "29776c198ae3"
down_revision = "0d0131124b2d"
branch_labels = None
depends_on = None

old_status_code = postgresql.ENUM(
    "PENDING", "QUEUED", "SUCCESS", "ERROR", name="form_job_item_status_code"
)

new_status_code = postgresql.ENUM(
    "PENDING", "QUEUED", "SUCCESS", "ERROR", "RUNNING", name="form_job_item_status_code"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE form_job_item_status_code ADD VALUE 'RUNNING'")
    op.add_column(
        "form_job_items", sa.Column("started_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "form_job_items", sa.Column("ended_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_job_items", "ended_at")
    op.drop_column("form_job_items", "started_at")
    # Postgresql not support drop a value of enum type

    # Change column type to varchar
    op.execute(
        'ALTER TABLE form_job_items ALTER COLUMN "status_code" '
        'TYPE varchar USING "status_code"::varchar'
    )

    # Update new value of enum type to NULL
    op.execute(
        "UPDATE form_job_items set status_code=NULL WHERE status_code = 'RUNNING'"
    )

    # Drop new type
    new_status_code.drop(op.get_bind())

    # Re create old type
    old_status_code.create(op.get_bind())

    # Change column type to old type
    op.execute(
        "ALTER TABLE form_job_items ALTER COLUMN "
        "status_code TYPE form_job_item_status_code"
        " USING status_code::text::form_job_item_status_code"
    )

    # ### end Alembic commands ###
