"""fix media_codes columns type

Revision ID: e291bc4e3ca6
Revises: 878419ef4008
Create Date: 2023-07-21 03:03:35.765118

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e291bc4e3ca6"
down_revision = "878419ef4008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE companies ALTER COLUMN press_release_media_codes "
        "TYPE VARCHAR(255)[] USING press_release_media_codes::varchar(255)[]"
    )
    op.execute(
        "ALTER TABLE companies ALTER COLUMN recruit_media_codes "
        "TYPE VARCHAR(255)[] USING recruit_media_codes::varchar(255)[]"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    op.alter_column(
        "companies", "recruit_media_codes", type_=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "companies",
        "press_release_media_codes",
        type_=sa.VARCHAR(length=255),
        nullable=True,
    )
