"""Added column groups table

Revision ID: f4cb7f43c874
Revises: 5352cec01e62
Create Date: 2023-06-21 09:33:03.537041

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f4cb7f43c874"
down_revision = "5352cec01e62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("default_flag", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "default_flag")
    # ### end Alembic commands ###
