"""update team credits table

Revision ID: 0aab184370ef
Revises: 3d2c1ede1998
Create Date: 2023-11-20 08:47:08.382133

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0aab184370ef"
down_revision = "3d2c1ede1998"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE servicecode ADD VALUE 'EMAIL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team_credits",
        "service_code",
        existing_type=sa.Enum("CPN", "PERSON", "MSG", name="servicecode"),
        nullable=True,
    )
    # ### end Alembic commands ###
