"""update companies table

Revision ID: fb1a30a364d5
Revises: a8b8ba823549
Create Date: 2023-04-25 08:27:11.254375

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fb1a30a364d5"
down_revision = "a8b8ba823549"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "estabilish_at", new_column_name="establish_at")
    op.add_column(
        "companies",
        sa.Column("this_month_doda_recruits_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "this_month_doda_recruits_count")
    op.alter_column("companies", "establish_at", new_column_name="estabilish_at")
    # ### end Alembic commands ###
