"""create mail jobs table

Revision ID: 711903c8ddf5
Revises: 0aab184370ef
Create Date: 2023-11-22 03:39:06.161502

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "711903c8ddf5"
down_revision = "0aab184370ef"
branch_labels = None
depends_on = None

status_code = postgresql.ENUM(
    "PENDING",
    "QUEUED",
    "RUNNING_SUCCESS",
    "RUNNING_ERROR",
    "DONE_SUCCESS",
    "DONE_ERROR",
    name="mail_job_status_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mail_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("placeholder_id", sa.Integer(), nullable=True),
        sa.Column("target_collection_id", sa.Integer(), nullable=True),
        sa.Column("exclude_collection_id", sa.Integer(), nullable=True),
        sa.Column("approach_ng_flag", sa.Integer(), nullable=True),
        sa.Column("schedule_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("max_resend_code", sa.String(length=20), nullable=True),
        sa.Column("status_code", status_code, nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mail_jobs")
    # ### end Alembic commands ###
