"""add cloumn teamplate id form job table

Revision ID: 49bd565e436e
Revises: acbb13f3d864
Create Date: 2023-05-23 04:12:00.401296

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "49bd565e436e"
down_revision = "acbb13f3d864"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_jobs", sa.Column("template_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_jobs", "template_id")
    # ### end Alembic commands ###
