"""create recruit_category_map table

Revision ID: be6a3fbb68ce
Revises: e717b707a725
Create Date: 2023-03-06 03:47:26.143161

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "be6a3fbb68ce"
down_revision = "e717b707a725"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recruit_category_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recruit_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recruit_category_map")
    # ### end Alembic commands ###
