"""Updated scenario_notification_items table

Revision ID: 3d2c1ede1998
Revises: ff823eaf11ad
Create Date: 2023-10-26 07:10:36.260013

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d2c1ede1998"
down_revision = "ff823eaf11ad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_notification_items",
        sa.Column("media_internal_id", sa.String(length=256), nullable=True),
    )
    op.add_column(
        "scenario_notification_items",
        sa.Column("media_code", sa.String(length=20), nullable=True),
    )
    op.drop_column("scenario_notification_items", "recruit_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenario_notification_items",
        sa.Column("recruit_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("scenario_notification_items", "media_code")
    op.drop_column("scenario_notification_items", "media_internal_id")
    # ### end Alembic commands ###
