"""add recruit_media_code to companies table

Revision ID: 83504171c7e7
Revises: 43fb92bbfdd5
Create Date: 2023-07-11 06:24:36.383504

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "83504171c7e7"
down_revision = "43fb92bbfdd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column("recruit_media_codes", sa.String(length=255), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "recruit_media_codes")
    # ### end Alembic commands ###
