"""alter person career and education, add current_flag

Revision ID: f04d642c2ba5
Revises: 95a4b031a907
Create Date: 2023-09-18 08:19:19.968076

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f04d642c2ba5"
down_revision = "95a4b031a907"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person_careers", sa.Column("current_flag", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "person_educations", sa.Column("current_flag", sa.Boolean(), nullable=True)
    )
    op.alter_column("person_careers", "role_name", type_=sa.TEXT(), nullable=True)
    op.alter_column("person_careers", "role_code", type_=sa.TEXT(), nullable=True)
    op.add_column(
        "person_careers", sa.Column("career_id", sa.VARCHAR(64), nullable=True)
    )
    op.drop_constraint("person_career_unique_key", "person_careers", type_="unique")
    op.create_unique_constraint(
        "person_career_unique_key",
        "person_careers",
        ["media_code", "person_uuid", "career_id", "start_at"],
    )
    op.add_column(
        "person_educations", sa.Column("education_id", sa.VARCHAR(64), nullable=True)
    )
    op.drop_constraint(
        "person_education_unique_key", "person_educations", type_="unique"
    )
    op.create_unique_constraint(
        "person_education_unique_key",
        "person_educations",
        ["media_code", "person_uuid", "education_id", "start_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("person_career_unique_key", "person_careers", type_="unique")
    op.create_unique_constraint(
        "person_career_unique_key",
        "person_careers",
        [
            "person_uuid",
            "company_id",
            "company_name",
            "start_at",
            "role_name",
            "description",
            "media_code",
        ],
    )
    op.drop_column("person_careers", "career_id")
    op.drop_constraint(
        "person_education_unique_key", "person_educations", type_="unique"
    )
    op.create_unique_constraint(
        "person_education_unique_key",
        "person_educations",
        [
            "person_uuid",
            "school_name",
            "start_at",
            "major",
            "description",
            "media_code",
        ],
    )
    op.drop_column("person_educations", "education_id")
    op.alter_column("person_careers", "role_name", type_=sa.VARCHAR(255), nullable=True)
    op.alter_column("person_careers", "role_code", type_=sa.VARCHAR(20), nullable=True)
    op.drop_column("person_educations", "current_flag")
    op.drop_column("person_careers", "current_flag")
