"""alter companies add unique key and change type of capital and revenue

Revision ID: 29799b1c0315
Revises: e843c86d5d44
Create Date: 2023-05-30 10:53:33.750471

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "29799b1c0315"
down_revision = "e843c86d5d44"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "companies_corporate_number_unique", "companies", ["corporate_number"]
    )
    op.alter_column(
        "companies", "postal_code", type_=postgresql.VARCHAR(20), nullable=True
    )
    op.alter_column("companies", "capital", type_=sa.BIGINT(), nullable=True)
    op.alter_column("companies", "revenue", type_=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("companies", "revenue", type_=sa.INT(), nullable=True)
    op.alter_column("companies", "capital", type_=sa.INT(), nullable=True)
    op.alter_column("companies", "postal_code", type_=sa.INT(), nullable=True)
    op.drop_constraint("companies_corporate_number_unique", "companies", type_="unique")
    # ### end Alembic commands ###
