"""update recruit, article add source url

Revision ID: 44bf61ef71c8
Revises: ba932ec0e57b
Create Date: 2024-01-05 07:46:27.723877

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "44bf61ef71c8"
down_revision = "ba932ec0e57b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "press_releases",
        sa.Column("source_article_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "recruits",
        sa.Column("source_recruit_url", sa.String(length=1024), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruits", "source_recruit_url")
    op.drop_column("press_releases", "source_article_url")
    # ### end Alembic commands ###
