"""update contrainst unique email to unique when deleted_at not null

Revision ID: 2bb1c176628a
Revises: a428946dc22c
Create Date: 2025-07-11 03:08:00.581660

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2bb1c176628a"
down_revision = "aa62335ea208"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "unique_active_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "unique_active_email",
        table_name="users",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
