"""update default linkedin credit

Revision ID: 6df88f451474
Revises: 777817de1e84
Create Date: 2025-10-14 04:42:16.114394

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6df88f451474"
down_revision = "777817de1e84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE plans SET linkedin_connect_quota = 0")
    op.execute("UPDATE plans SET linkedin_msg_quota = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE plans SET linkedin_connect_quota = 3")
    op.execute("UPDATE plans SET linkedin_msg_quota = 20")
    # ### end Alembic commands ###
