"""empty message

Revision ID: 9f6c6d30835e
Revises: c6628f19dec3
Create Date: 2025-04-03 07:47:45.800292

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f6c6d30835e'
down_revision = 'c6628f19dec3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('phone_verify', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('phone_verify_method_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'phone_verify_method_quality')
    op.drop_column('companies', 'phone_verify')
    # ### end Alembic commands ###
