"""empty message

Revision ID: 8baa348176ac
Revises: cbecdeeca039
Create Date: 2025-02-10 04:34:54.144572

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8baa348176ac'
down_revision = 'cbecdeeca039'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mail_templates', sa.Column('title', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mail_templates', 'title')
    # ### end Alembic commands ###
