"""add sequence_campaign_settings table

Revision ID: 46ae6a64fc50
Revises: 262806f003ae
Create Date: 2025-06-30 08:28:44.113906

"""
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision = "46ae6a64fc50"
down_revision = "0a2f7d428e48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sequencepersonstage_enum = ENUM(
        "COLD",
        "APPROACHING",
        "BAD_DATA",
        "DO_NOT_CONTACT",
        "REPLIED",
        "UNRESPONSIVE",
        name="sequencepersonstage",
        create_type=False,
    )
    sequencepersonstage_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "sequence_campaign_settings",
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("sequence_campaign_id", sa.Integer(), nullable=True),
        sa.Column("days_until_unresponsive", sa.Integer(), nullable=True),
        sa.Column(
            "stage_list_as_not_sent",
            sa.ARRAY(sequencepersonstage_enum),
            nullable=True,
        ),
        sa.Column("is_finished_when_replied", sa.Boolean(), nullable=True),
        sa.Column("is_finished_when_unsubscribed", sa.Boolean(), nullable=True),
        sa.Column("is_status_change_when_bounced", sa.Boolean(), nullable=True),
        sa.Column("cc_list", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("bcc_list", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence_campaign_settings")
    # ### end Alembic commands ###
