"""empty message

Revision ID: c9957eb6d58f
Revises: 38fb1c4b26ae
Create Date: 2025-06-25 21:08:14.737677

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c9957eb6d58f"
down_revision = "03a370ae3107"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_campaigns", sa.Column("schedule_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_campaigns", "schedule_id")
    # ### end Alembic commands ###
