"""empty message

Revision ID: 2c1aaaf68087
Revises: 60ccbdb06c36
Create Date: 2025-02-20 03:34:21.826959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1aaaf68087'
down_revision = 'f945a40b8ea0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_mail_histories',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('sequence_mailbox_id', sa.Integer(), nullable=True),
    sa.Column('sequence_person_id', sa.Integer(), nullable=True),
    sa.Column('sequence_step_id', sa.Integer(), nullable=True),
    sa.Column('sequence_campaign_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SKIPPED', 'SCHEDULED', 'OPENED', 'DRAFT', 'REPLIED', name='mailhistorystatus'), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sent_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence_mail_histories')
    # ### end Alembic commands ###
