"""Add field to sequence person

Revision ID: cbecdeeca039
Revises: de4df759d65a
Create Date: 2025-02-07 07:41:25.802332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cbecdeeca039"
down_revision = "de4df759d65a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_persons", sa.Column("status", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "sequence_persons", sa.Column("current_step", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sequence_persons", sa.Column("stage", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_persons", "stage")
    op.drop_column("sequence_persons", "current_step")
    op.drop_column("sequence_persons", "status")
    # ### end Alembic commands ###
