"""add roles column into persons table

Revision ID: e30478757879
Revises: 0a9cc2d1e992
Create Date: 2025-02-25 04:47:14.080553

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e30478757879"
down_revision = "0a9cc2d1e992"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "persons",
        sa.Column("sub_group_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "sub_group_codes")
    # ### end Alembic commands ###
