"""empty message

Revision ID: 10e9695de56d
Revises: f6f2c1bae848
Create Date: 2025-02-13 06:34:40.290779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10e9695de56d'
down_revision = 'f6f2c1bae848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mail_templates', sa.Column('is_reply_to_previous_thread', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mail_templates', 'is_reply_to_previous_thread')
    # ### end Alembic commands ###
