"""add_funding_company_table

Revision ID: 6307b2c762b3
Revises: 9b9831b1ef75
Create Date: 2025-02-14 03:58:03.502754

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6307b2c762b3"
down_revision = "9b9831b1ef75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies",
        sa.Column(
            "three_month_funding_flags", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "six_month_funding_flags", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "twelve_month_funding_flags", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
    )
    op.add_column(
        "companies",
        sa.Column("all_funding_flags", sa.ARRAY(sa.String(length=255)), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("companies", "all_funding_flags")
    op.drop_column("companies", "twelve_month_funding_flags")
    op.drop_column("companies", "six_month_funding_flags")
    op.drop_column("companies", "three_month_funding_flags")
    # ### end Alembic commands ###
