"""update table campaigns and steps

Revision ID: de4df759d65a
Revises: ce15c97b752f
Create Date: 2025-02-05 10:22:44.252825

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de4df759d65a"
down_revision = "ce15c97b752f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    step_enum = postgresql.ENUM("MAIL_MANUAL", "MAIL_AUTO", name="steptype")
    step_enum.create(op.get_bind(), checkfirst=True)
    timing_enum = postgresql.ENUM("IMMEDIATE", "SCHEDULED", name="timingtype")
    timing_enum.create(op.get_bind(), checkfirst=True)
    schedule_enum = postgresql.ENUM("DAYS", "HOURS", "MINUTES", name="scheduleunit")
    schedule_enum.create(op.get_bind(), checkfirst=True)
    priority_enum = postgresql.ENUM("HIGH", "NORMAL", "LOW", name="priority")
    priority_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_campaign_steps", sa.Column("title", sa.Text(), nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("step_type", step_enum, nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("description", sa.Text(), nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("sequence_campaign_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("timing_type", timing_enum, nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("schedule_unit", schedule_enum, nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("schedule_value", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("priority", priority_enum, nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("memo", sa.Text(), nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("is_email_limit_enabled", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("email_limit_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("is_skip_enabled", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("skip_after_days", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps",
        sa.Column("mail_template_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "sequence_campaign_steps", sa.Column("order", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sequence_campaigns", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "sequence_campaigns", sa.Column("team_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sequence_campaigns", sa.Column("owner_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_campaigns", "is_active")
    op.drop_column("sequence_campaign_steps", "order")
    op.drop_column("sequence_campaign_steps", "is_active")
    op.drop_column("sequence_campaign_steps", "mail_template_id")
    op.drop_column("sequence_campaign_steps", "skip_after_days")
    op.drop_column("sequence_campaign_steps", "is_skip_enabled")
    op.drop_column("sequence_campaign_steps", "email_limit_count")
    op.drop_column("sequence_campaign_steps", "is_email_limit_enabled")
    op.drop_column("sequence_campaign_steps", "memo")
    op.drop_column("sequence_campaign_steps", "priority")
    op.drop_column("sequence_campaign_steps", "schedule_value")
    op.drop_column("sequence_campaign_steps", "schedule_unit")
    op.drop_column("sequence_campaign_steps", "timing_type")
    op.drop_column("sequence_campaign_steps", "sequence_campaign_id")
    op.drop_column("sequence_campaign_steps", "description")
    op.drop_column("sequence_campaign_steps", "step_type")
    op.drop_column("sequence_campaign_steps", "title")
    op.drop_column("sequence_campaigns", "team_id")
    op.drop_column("sequence_campaigns", "owner_id")
    # ### end Alembic commands ###
