"""change type value salesforce_person_id

Revision ID: cd02681b3b0f
Revises: bc8f6866d4db
Create Date: 2025-04-18 11:15:55.308943

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cd02681b3b0f"
down_revision = "bc8f6866d4db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_person_pull_histories",
        "salesforce_person_id",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_raw_persons",
        "salesforce_person_id",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_raw_persons",
        "salesforce_person_id",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_person_pull_histories",
        "salesforce_person_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
