"""Drop table user-column-settings

Revision ID: 2f2cd6538d5e
Revises: aa46d9523bab
Create Date: 2025-03-20 10:13:24.528897

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2f2cd6538d5e"
down_revision = "aa46d9523bab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_column_settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_column_settings",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("model_code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "column_settings",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="user_column_settings_pkey"),
    )
    # ### end Alembic commands ###
