"""empty message

Revision ID: 78b8288fedbc
Revises: 24d4944f17bc
Create Date: 2025-03-27 06:15:21.896376

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "78b8288fedbc"
down_revision = "24d4944f17bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_histories",
        sa.Column("tracking_token", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_histories", "tracking_token")
    # ### end Alembic commands ###
