"""Add table user-column-settings

Revision ID: b2bcb154140c
Revises: 643fb6e34b55
Create Date: 2025-03-18 10:05:51.372216

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2bcb154140c"
down_revision = "643fb6e34b55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_column_settings",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("model_code", sa.String(), nullable=True),
        sa.Column("column_settings", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_column_settings")
    # ### end Alembic commands ###
