"""create index in hubspot_company_pull_histories table

Revision ID: fe9db7ca4f75
Revises: 39fae504e3a7
Create Date: 2025-05-05 09:16:18.634854

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe9db7ca4f75"
down_revision = "39fae504e3a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_hubspot_company_pull_histories_id",
        "hubspot_company_pull_histories",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_hubspot_company_pull_histories_id",
        table_name="hubspot_company_pull_histories",
    )
    # ### end Alembic commands ###
