"""create_hubspot_person_histories_table

Revision ID: 767c600eaba7
Revises: 9784ce12d2d9
Create Date: 2025-01-21 04:18:37.733237

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "767c600eaba7"
down_revision = "9784ce12d2d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hubspot_person_multiple_company_histories",
        sa.Column("hubspot_person_log_id", sa.Integer(), nullable=True),
        sa.Column(
            "matched_company_ids", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_pull_person_histories",
        sa.Column("hubspot_person_id", sa.String(length=50), nullable=True),
        sa.Column("hubspot_company_id", sa.String(length=50), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("log_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hubspot_pull_person_histories")
    op.drop_table("hubspot_person_multiple_company_histories")
    # ### end Alembic commands ###
