"""update form job item status code

Revision ID: 38fb1c4b26ae
Revises: 0b870bf59a08
Create Date: 2025-06-25 08:09:39.961740

"""
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "38fb1c4b26ae"
down_revision = "0b870bf59a08"
branch_labels = None
depends_on = None

old_status_code = postgresql.ENUM(
    "PENDING", "QUEUED", "SUCCESS", "ERROR", "RUNNING", name="form_job_item_status_code"
)

new_status_code = postgresql.ENUM(
    "PENDING",
    "QUEUED",
    "SUCCESS",
    "ERROR",
    "RUNNING",
    "NOT_SEND",
    name="form_job_item_status_code",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE form_job_item_status_code ADD VALUE 'NOT_SEND'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgresql not support drop a value of enum type

    # Change column type to varchar
    op.execute(
        'ALTER TABLE form_job_items ALTER COLUMN "status_code" '
        'TYPE varchar USING "status_code"::varchar'
    )

    # Update new value of enum type to NULL
    op.execute(
        "UPDATE form_job_items set status_code=NULL WHERE status_code = 'NOT_SEND'"
    )

    # Drop new type
    new_status_code.drop(op.get_bind())

    # Re create old type
    old_status_code.create(op.get_bind())

    # Change column type to old type
    op.execute(
        "ALTER TABLE form_job_items ALTER COLUMN "
        "status_code TYPE form_job_item_status_code"
        " USING status_code::text::form_job_item_status_code"
    )
    # ### end Alembic commands ###
