"""add column config_step_done in mailboxes table

Revision ID: 9e24f4c3f9f2
Revises: b7e40ce8ff50
Create Date: 2025-04-09 09:07:43.664181

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9e24f4c3f9f2"
down_revision = "b7e40ce8ff50"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mailboxes",
        sa.Column("config_step_done", sa.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mailboxes", "config_step_done")
    # ### end Alembic commands ###
