"""add column is_rescheduled in table sequence_mail_histories

Revision ID: aa62335ea208
Revises: 53f422ad9e56
Create Date: 2025-07-14 06:10:23.318464

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa62335ea208"
down_revision = "53f422ad9e56"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_histories",
        sa.Column("is_rescheduled", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_histories", "is_rescheduled")
    # ### end Alembic commands ###
