"""update linkedin_accounts table

Revision ID: 27fca2d1b292
Revises: cf45f4864d01
Create Date: 2025-07-27 16:06:04.612486

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "27fca2d1b292"
down_revision = "4fd0fb9680d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linkedin_accounts",
        sa.Column("account_name", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "linkedin_accounts",
        sa.Column("public_identifier", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "linkedin_accounts",
        sa.Column("account_type", sa.String(length=128), nullable=True),
    )
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'OK'")
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'RECONNECTED'")
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'CONNECTING'")
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'STOPPED'")
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'ERROR'")
    op.execute(
        "ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'SYNC_SUCCESS'"
    )
    op.execute("ALTER TYPE linkedinaccountstatus ADD VALUE IF NOT EXISTS 'DELETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Bước 1: Update các bản ghi dùng giá trị mới về giá trị hợp lệ cũ
    op.execute(
        """
        UPDATE linkedin_accounts
        SET status = 'CREATION_SUCCESS'
        WHERE status IN (
            'OK', 'RECONNECTED', 'CONNECTING',
            'STOPPED', 'SYNC_SUCCESS', 'DELETED', 'ERROR'
        )
    """
    )

    # Bước 2: Chuyển cột status sang kiểu TEXT tạm thời
    op.execute("ALTER TABLE linkedin_accounts ALTER COLUMN status TYPE TEXT")

    # Bước 3: Tạo lại enum cũ với 2 giá trị ban đầu
    op.execute(
        "CREATE TYPE linkedinaccountstatus_old AS ENUM ('CREDENTIALS', 'CREATION_SUCCESS')"
    )

    # Bước 4: Chuyển kiểu status về enum cũ
    op.execute(
        """
        ALTER TABLE linkedin_accounts
        ALTER COLUMN status
        TYPE linkedinaccountstatus_old
        USING status::linkedinaccountstatus_old
    """
    )

    # Bước 5: Xóa enum hiện tại (có giá trị mở rộng)
    op.execute("DROP TYPE linkedinaccountstatus")

    # Bước 6: Đổi tên enum cũ về tên ban đầu
    op.execute("ALTER TYPE linkedinaccountstatus_old RENAME TO linkedinaccountstatus")

    # Bước 7: Xóa các cột đã thêm
    op.drop_column("linkedin_accounts", "account_type")
    op.drop_column("linkedin_accounts", "public_identifier")
    op.drop_column("linkedin_accounts", "account_name")
    # ### end Alembic commands ###
