"""create hubspot intergration table

Revision ID: a8e096dcfed5
Revises: 44bf61ef71c8
Create Date: 2025-01-10 03:58:01.857085

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8e096dcfed5"
down_revision = "44bf61ef71c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_custom_field_settings",
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("field_type", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_custom_fields",
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_companies",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_company_id", sa.Integer(), nullable=True),
        sa.Column("predefined_fields", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_associations",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_company_id", sa.Integer(), nullable=True),
        sa.Column("association_to", sa.Integer(), nullable=True),
        sa.Column("association_type_id", sa.Integer(), nullable=True),
        sa.Column("association_category", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_custom_field_settings",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_custom_fields",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_company_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("value", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_field_mappings",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_field", sa.String(length=255), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("field_class", sa.String(length=255), nullable=True),
        sa.Column("overwrite_flag", sa.Boolean(), nullable=True),
        sa.Column("autofill_flag", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_multiple_pull_histories",
        sa.Column(
            "matched_company_ids", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_multiple_push_histories",
        sa.Column(
            "matched_company_ids", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_not_found_pull_histories",
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_not_found_push_histories",
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_pull_histories",
        sa.Column("hubspot_company_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("error_detail_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_push_histories",
        sa.Column("ss_company_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("error_detail_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_company_sync_histories",
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("sync_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_integrations",
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("company_merge_strategy", sa.String(length=255), nullable=True),
        sa.Column("person_merge_strategy", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_raw_companies",
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_company_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hubspot_synced_companies",
        sa.Column("ss_company_id", sa.Integer(), nullable=True),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("ss_company_fields", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("overwrite_flag", sa.Boolean(), nullable=True),
        sa.Column("autofill_flag", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hubspot_synced_companies")
    op.drop_table("hubspot_raw_companies")
    op.drop_table("hubspot_integrations")
    op.drop_table("hubspot_company_sync_histories")
    op.drop_table("hubspot_company_push_histories")
    op.drop_table("hubspot_company_pull_histories")
    op.drop_table("hubspot_company_not_found_push_histories")
    op.drop_table("hubspot_company_not_found_pull_histories")
    op.drop_table("hubspot_company_multiple_push_histories")
    op.drop_table("hubspot_company_multiple_pull_histories")
    op.drop_table("hubspot_company_field_mappings")
    op.drop_table("hubspot_company_custom_fields")
    op.drop_table("hubspot_company_custom_field_settings")
    op.drop_table("hubspot_company_associations")
    op.drop_table("hubspot_companies")
    op.drop_table("company_custom_fields")
    op.drop_table("company_custom_field_settings")
    # ### end Alembic commands ###
