"""change type column ss_company_id

Revision ID: 2a2a8ea36f21
Revises: 0688ab7a408a
Create Date: 2025-04-15 09:37:45.323352

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a2a8ea36f21"
down_revision = "0688ab7a408a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_company_push_histories",
        "ss_company_id",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_manual_push_companies",
        "ss_company_id",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_synced_companies",
        "ss_company_id",
        existing_type=sa.INTEGER(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_synced_companies",
        "ss_company_id",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_manual_push_companies",
        "ss_company_id",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "salesforce_company_push_histories",
        "ss_company_id",
        existing_type=sa.Text(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
