"""empty message

Revision ID: af662b668941
Revises: 2aa2478722aa
Create Date: 2025-03-20 07:17:26.399127

"""

from alembic import op

from app.models.sequence.mail_history import MAIL_HISTORY_VIEW_NAME

# revision identifiers, used by Alembic.
revision = "af662b668941"
down_revision = "8955fa641c8d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP VIEW {MAIL_HISTORY_VIEW_NAME};")
    op.execute(
        f"""
    CREATE OR REPLACE VIEW {MAIL_HISTORY_VIEW_NAME} AS (
        SELECT smh.id AS mail_history_id,
            smh.sequence_person_id,
            sp."name" AS sequence_person_name,
            smh.sequence_campaign_id,
            sc."name" AS sequence_campaign_name,
            smh.sequence_step_id,
            scs."order" AS sequence_step_order,
            smh.sequence_mailbox_id,
            sm.email AS email_from,
            smh.title,
            smh."content",
            smh.email_to,
            smh.status,
            smh.sent_at,
            smh.sent_by,
            u."name" AS sender_name,
            'HISTORY' AS mail_history_type,
            smh.process_status AS process_status
        FROM sequence_mail_histories smh
        JOIN sequence_campaign_steps scs ON smh.sequence_step_id = scs.id
        JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
        JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
        JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
        LEFT JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
        LEFT JOIN users u ON smh.sent_by = u.id
        WHERE smh.deleted_at IS NULL
        UNION
            SELECT NULL as mail_history_id,
                tmp.sequence_person_id,
                tmp.sequence_person_name,
                tmp.sequence_campaign_id,
                tmp.sequence_campaign_name,
                tmp.next_sequence_step_id AS sequence_step_id,
                tmp.sequence_step_order,
                tmp.sequence_mailbox_id,
                tmp.email_from,
                tmp.mail_template_title AS title,
                tmp.mail_template_content AS content,
                tmp.email_to,
                'SCHEDULED' AS status,
                CASE
                    WHEN tmp.timing_type = 'SCHEDULED'
                            AND tmp.step_type = 'MAIL_AUTO' THEN tmp.sent_at + (tmp.schedule_value || ' ' || tmp.schedule_unit)::interval
                    WHEN tmp.timing_type = 'IMMEDIATE'::timingtype
                            AND tmp.step_type = 'MAIL_AUTO'::steptype THEN tmp.sent_at
                END AS sent_at,
                tmp.sent_by,
                tmp.sender_name,
                'FUTURE' AS mail_history_type,
                NULL AS process_status
            FROM
            (SELECT smh.*,
                    scs.timing_type,
                    scs.schedule_unit,
                    scs.schedule_value,
                    scs.step_type,
                    scs."is_active" AS is_sequence_step_active,
                    sp.name AS sequence_person_name,
                    sc.name AS sequence_campaign_name,
                    scp.status AS sequence_person_status,
                    scs."order" AS sequence_step_order,
                    sm.email AS email_from,
                    smt.title AS mail_template_title,
                    u."name" AS sender_name,
                    smt."content" AS mail_template_content,
                    ROW_NUMBER() OVER (PARTITION BY smh.sequence_campaign_id, smh.sequence_person_id
                                        ORDER BY scs.order DESC) AS row_num
            FROM sequence_mail_histories smh
            LEFT JOIN sequence_campaign_steps scs ON smh.next_sequence_step_id = scs.id
            LEFT JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
            JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
            JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
            JOIN sequence_campaign_persons scp ON scp.sequence_person_id = sp.id
            LEFT JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
            LEFT JOIN users u ON smh.sent_by = u.id) tmp
            WHERE tmp.row_num = 1
            AND tmp.deleted_at IS NULL
            AND tmp.sequence_person_status = 'ACTIVE'
            AND tmp.is_sequence_step_active = TRUE
            AND tmp.next_sequence_step_id IS NOT NULL
        UNION
            SELECT NULL as mail_history_id,
                sp.id AS sequence_person_id,
                sp.name AS sequence_person_name,
                sc.id AS sequence_campaign_id,
                sc.name AS sequence_campaign_name,
                scs.id AS sequence_step_id,
                scs."order" AS sequence_step_order,
                tmp.id AS sequence_mailbox_id,
                tmp.email AS email_from,
                smt.title,
                smt.content,
                sp.email AS email_to,
                'SCHEDULED'::mailhistorystatus AS status,
                CASE
                    WHEN scs.timing_type = 'SCHEDULED'::timingtype
                            AND scs.step_type = 'MAIL_AUTO'::steptype 
                            AND scs.created_at > sp.created_at THEN scs.created_at + (((scs.schedule_value || ' '::text) || scs.schedule_unit)::interval)
                    WHEN scs.timing_type = 'SCHEDULED'::timingtype
                            AND scs.step_type = 'MAIL_AUTO'::steptype 
                            AND sp.created_at > scs.created_at THEN sp.created_at + (((scs.schedule_value || ' '::text) || scs.schedule_unit)::interval)
                    WHEN scs.timing_type = 'IMMEDIATE'::timingtype
                            AND scs.step_type = 'MAIL_AUTO'::steptype
                            AND scs.created_at > sp.created_at THEN scs.created_at
                    WHEN scs.timing_type = 'IMMEDIATE'::timingtype
                            AND scs.step_type = 'MAIL_AUTO'::steptype
                            AND sp.created_at > scs.created_at THEN sp.created_at
                    ELSE NULL::timestamp WITHOUT TIME ZONE
                END AS sent_at,
                u.id AS sent_by,
                u.name AS sender_name,
                'FIRST'::text AS mail_history_type,
                NULL AS process_status
            FROM sequence_campaigns sc
            JOIN users u ON sc.created_by = u.id
            JOIN sequence_persons sp ON sc.id = sp.sequence_campaign_id
            JOIN sequence_campaign_steps scs ON sc.id = scs.sequence_campaign_id
            AND scs."order" = 1
            JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
            JOIN
            (SELECT sm.user_id,
                    sm.team_id,
                    sm.email,
                    sm.password,
                    sm.host,
                    sm.port,
                    sm.emails_sent_per_day,
                    sm.emails_sent_per_hour,
                    sm.delay_between_emails,
                    sm.email_signature,
                    sm.opt_out_message_after_signature,
                    sm.is_opt_out_message_after_signature,
                    sm.is_open_tracking,
                    sm.is_click_tracking,
                    sm.is_include_one_click_unsubscribe_headers,
                    sm.created_at,
                    sm.created_by,
                    sm.updated_at,
                    sm.updated_by,
                    sm.deleted_at,
                    sm.deleted_by,
                    sm.id,
                    sm.imap_email,
                    sm.imap_password,
                    sm.imap_host,
                    sm.imap_port,
                    sm.google_refresh_token,
                    sm.mailbox_type,
                    row_number() OVER (PARTITION BY sm.user_id
                                        ORDER BY sm.id) AS row_num
            FROM sequence_mailboxes sm) tmp ON tmp.user_id = sc.created_by
            AND tmp.row_num = 1
            LEFT JOIN sequence_mail_histories smh ON smh.sequence_campaign_id = sc.id
            AND smh.sequence_person_id = sp.id
            AND smh.sequence_step_id = scs.id
            WHERE smh.id IS NULL AND scs.is_active = TRUE
    );
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP VIEW {MAIL_HISTORY_VIEW_NAME};")
    # ### end Alembic commands ###
