"""add initial_password in table users

Revision ID: e203441c71fe
Revises: 0688ab7a408a
Create Date: 2025-04-15 08:36:05.972128

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e203441c71fe"
down_revision = "6614871b7e7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("initial_password", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "initial_password")
    # ### end Alembic commands ###
