"""empty message

Revision ID: af662b668940
Revises: 2aa2478722aa
Create Date: 2025-03-20 07:17:26.399127

"""

from alembic import op
import sqlalchemy as sa

from app.models.sequence.mail_history import MAIL_HISTORY_VIEW_NAME

# revision identifiers, used by Alembic.
revision = "af662b668940"
down_revision = "e30444e794b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_histories",
        sa.Column("next_sequence_step_id", sa.Integer(), nullable=True),
    )
    op.execute(
        f"""
    CREATE VIEW {MAIL_HISTORY_VIEW_NAME} AS (
        SELECT
            smh.sequence_person_id,
            sp."name" AS sequence_person_name,
            smh.sequence_campaign_id,
            sc."name" AS sequence_campaign_name,
            smh.sequence_step_id,
            scs."order" AS sequence_step_order,
            smh.sequence_mailbox_id,
            sm.email AS email_from,
            smh.title,
            smh."content",
            smh.email_to,
            smh.status,
            smh.sent_at,
            smh.sent_by,
            u."name" AS sender_name,
            'HISTORY' AS mail_history_type
        FROM
            sequence_mail_histories smh
            JOIN sequence_campaign_steps scs ON smh.sequence_step_id = scs.id
            JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
            JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
            JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
            LEFT JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
            LEFT JOIN users u ON smh.sent_by = u.id
        WHERE
            smh.deleted_at IS NULL
        UNION
        SELECT
            tmp.sequence_person_id,
            tmp.sequence_person_name,
            tmp.sequence_campaign_id,
            tmp.sequence_campaign_name,
            tmp.next_sequence_step_id AS sequence_step_id,
            tmp.sequence_step_order,
            tmp.sequence_mailbox_id,
            tmp.email_from,
            tmp.mail_template_title AS title,
            tmp.mail_template_content AS content,
            tmp.email_to,
            'SCHEDULED' AS status,
            CASE
                WHEN tmp.timing_type = 'SCHEDULED' AND tmp.step_type = 'MAIL_AUTO' THEN tmp.sent_at + (tmp.schedule_value || ' ' || tmp.schedule_unit)::interval
            END AS sent_at,
            tmp.sent_by,
            tmp.sender_name,
            'FUTURE' AS mail_history_type
        FROM
            (
                SELECT
                    smh.*,
                    scs.timing_type,
                    scs.schedule_unit,
                    scs.schedule_value,
                    scs.step_type,
                    sp.name AS sequence_person_name,
                    sc.name AS sequence_campaign_name,
                    scp.status AS sequence_person_status,
                    scs."order" AS sequence_step_order,
                    sm.email AS email_from,
                    smt.title AS mail_template_title,
                    u."name" AS sender_name,
                    smt."content" AS mail_template_content,
                    ROW_NUMBER() OVER (
                        PARTITION BY
                            smh.sequence_campaign_id,
                            smh.sequence_person_id
                        ORDER BY
                            scs.order DESC
                    ) AS row_num
                FROM
                    sequence_mail_histories smh
                    LEFT JOIN sequence_campaign_steps scs ON smh.next_sequence_step_id = scs.id
                    LEFT JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
                    JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
                    JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
                    JOIN sequence_campaign_persons scp ON scp.sequence_person_id = sp.id
                    LEFT JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
                    LEFT JOIN users u ON smh.sent_by = u.id
            ) tmp
        WHERE
            tmp.row_num = 1
            AND tmp.deleted_at is NULL
            AND tmp.sequence_person_status = 'ACTIVE'
            AND tmp.next_sequence_step_id IS NOT NULL
    );
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_histories", "next_sequence_step_id")
    op.execute(f"DROP VIEW {MAIL_HISTORY_VIEW_NAME};")
    # ### end Alembic commands ###
