"""after table hubspot raw persons

Revision ID: 850520214504
Revises: 60ccbdb06c36
Create Date: 2025-02-20 06:27:08.779360

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "850520214504"
down_revision = "60ccbdb06c36"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hubspot_raw_persons",
        sa.Column("hubspot_team_id", sa.Integer(), nullable=True),
        sa.Column("integration_id", sa.Integer(), nullable=True),
        sa.Column("hubspot_person_id", sa.String(length=50), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hubspot_raw_persons")
    # ### end Alembic commands ###
