"""Add event table

Revision ID: 5f2c66f91490
Revises: b545746c3cd3
Create Date: 2025-04-22 03:40:41.399425

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "5f2c66f91490"
down_revision = "b545746c3cd3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("source_event_url", sa.String(length=1024), nullable=True),
        sa.Column("media_internal_id", sa.String(length=255), nullable=True),
        sa.Column("media_code", sa.String(length=20), nullable=True),
        sa.Column("corporate_number", sa.String(length=20), nullable=True),
        sa.Column("ingest_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("start_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("end_time", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "type", sa.Enum("EXPO", "OFFLINE", "ONLINE", name="typecode"), nullable=True
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_code", "media_internal_id", name="events_unique_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
