"""add_fields_to_sequence_campaign_persons

Revision ID: f4ce277b95de
Revises: 10e9695de56d
Create Date: 2025-02-13 09:35:29.330220

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f4ce277b95de"
down_revision = "10e9695de56d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_campaign_persons",
        sa.Column("reason", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "sequence_campaign_persons",
        sa.Column(
            "time_resumed",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_campaign_persons", "reason")
    op.drop_column("sequence_campaign_persons", "time_resumed")
    # ### end Alembic commands ###
