"""after column form schedule id in form job

Revision ID: ec1bb80a26d9
Revises: 628dbb112986
Create Date: 2025-06-18 06:59:26.353143

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ec1bb80a26d9"
down_revision = "628dbb112986"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form_jobs", sa.Column("form_schedule_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_jobs", "form_schedule_id")
    # ### end Alembic commands ###
