"""aflter table form schedule

Revision ID: 3b72e84fc1cb
Revises: 81404e8ace8c
Create Date: 2025-06-17 04:18:32.785230

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b72e84fc1cb"
down_revision = "81404e8ace8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_schedules",
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("time_zone", sa.String(length=255), nullable=True),
        sa.Column("is_skip_holiday", sa.Boolean(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("days_per_week", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_schedules")
    # ### end Alembic commands ###
