"""alter team add active_hubspot col

Revision ID: 60ccbdb06c36
Revises: 6307b2c762b3
Create Date: 2025-02-19 15:58:04.055376

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "60ccbdb06c36"
down_revision = "b5408578df7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("active_hubspot", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "active_hubspot")
    # ### end Alembic commands ###
