"""add avatar_path to users table

Revision ID: 8ec0cbbcb1f1
Revises: 4d6903ebda0a
Create Date: 2025-07-08 06:26:29.499940

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ec0cbbcb1f1"
down_revision = "373aa271b60a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar_path", sa.String(length=1024), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###
