"""create mail alias table

Revision ID: b7e40ce8ff50
Revises: b545746c3cd3
Create Date: 2025-04-08 11:38:34.542285

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b7e40ce8ff50"
down_revision = "b95b3227c5d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequence_mail_aliases",
        sa.Column("sequence_mailbox_id", sa.Integer(), nullable=True),
        sa.Column("alias_email", sa.String(length=128), nullable=True),
        sa.Column("alias_name", sa.String(length=128), nullable=True),
        sa.Column("alias_signature", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence_mail_aliases")
    # ### end Alembic commands ###
