"""empty message

Revision ID: 9e5f95b46cce
Revises: 97582576a957
Create Date: 2025-08-07 03:22:45.084742

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9e5f95b46cce"
down_revision = "97582576a957"
branch_labels = None
depends_on = None


old_plan_service_code = postgresql.ENUM(
    "LISTING",
    "CPN",
    "PERSON",
    "MSG",
    "FORM",
    "EMAIL",
    "CSV",
    "TELESALE",
    name="plan_service_code",
)

new_plan_service_code = postgresql.ENUM(
    "LISTING",
    "CPN",
    "PERSON",
    "MSG",
    "FORM",
    "EMAIL",
    "CSV",
    "TELESALE",
    "LINKEDIN_CONNECT",
    "LINKEDIN_MSG",
    name="plan_service_code",
)


old_service_code = postgresql.ENUM(
    "LISTING",
    "CPN",
    "PERSON",
    "MSG",
    "FORM",
    "EMAIL",
    "CSV",
    "TELESALE",
    name="servicecode",
)

new_service_code = postgresql.ENUM(
    "LISTING",
    "CPN",
    "PERSON",
    "MSG",
    "FORM",
    "EMAIL",
    "CSV",
    "TELESALE",
    "LINKEDIN_CONNECT",
    "LINKEDIN_MSG",
    name="servicecode",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plans", sa.Column("linkedin_connect_quota", sa.Integer(), nullable=True)
    )
    op.add_column("plans", sa.Column("linkedin_msg_quota", sa.Integer(), nullable=True))
    op.execute("ALTER TYPE plan_service_code ADD VALUE 'LINKEDIN_CONNECT'")
    op.execute("ALTER TYPE plan_service_code ADD VALUE 'LINKEDIN_MSG'")
    op.execute("ALTER TYPE servicecode ADD VALUE 'LINKEDIN_CONNECT'")
    op.execute("ALTER TYPE servicecode ADD VALUE 'LINKEDIN_MSG'")

    # Set default quota for all plans
    op.execute(
        """
        UPDATE plans
        SET linkedin_connect_quota = 3, linkedin_msg_quota = 20
        WHERE linkedin_connect_quota IS NULL AND linkedin_msg_quota IS NULL;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        'ALTER TABLE plans ALTER COLUMN "service_code" '
        'TYPE varchar USING "service_code"::varchar'
    )

    op.execute(
        'ALTER TABLE subcriptions ALTER COLUMN "service_code" '
        'TYPE varchar USING "service_code"::varchar'
    )
    op.execute(
        'ALTER TABLE team_credits ALTER COLUMN "service_code" '
        'TYPE varchar USING "service_code"::varchar'
    )
    op.execute(
        'ALTER TABLE downloaded_histories ALTER COLUMN "service_code" '
        'TYPE varchar USING "service_code"::varchar'
    )

    # Update new value of enum type to NULL
    op.execute(
        "UPDATE plans set service_code=NULL WHERE service_code IN ('LINKEDIN_CONNECT', 'LINKEDIN_MSG')"
    )
    op.execute(
        "UPDATE subcriptions set service_code=NULL WHERE service_code IN ('LINKEDIN_CONNECT', 'LINKEDIN_MSG')"
    )
    op.execute(
        "UPDATE team_credits set service_code=NULL WHERE service_code IN ('LINKEDIN_CONNECT', 'LINKEDIN_MSG')"
    )
    op.execute(
        "UPDATE downloaded_histories set service_code=NULL WHERE service_code IN ('LINKEDIN_CONNECT', 'LINKEDIN_MSG')"
    )

    # Drop new type
    new_plan_service_code.drop(op.get_bind())
    new_service_code.drop(op.get_bind())

    # Re create old type
    old_plan_service_code.create(op.get_bind())
    old_service_code.create(op.get_bind())

    # Change column type to old type
    op.execute(
        "ALTER TABLE plans ALTER COLUMN "
        "service_code TYPE plan_service_code"
        " USING service_code::text::plan_service_code"
    )
    op.execute(
        "ALTER TABLE subcriptions ALTER COLUMN "
        "service_code TYPE plan_service_code"
        " USING service_code::text::plan_service_code"
    )
    op.execute(
        "ALTER TABLE team_credits ALTER COLUMN "
        "service_code TYPE servicecode"
        " USING service_code::text::servicecode"
    )
    op.execute(
        "ALTER TABLE downloaded_histories ALTER COLUMN "
        "service_code TYPE servicecode"
        " USING service_code::text::servicecode"
    )

    op.drop_column("plans", "linkedin_msg_quota")
    op.drop_column("plans", "linkedin_connect_quota")
    # ### end Alembic commands ###
