"""Add request_interval_seconds to linkedin_accounts

Revision ID: e76422479733
Revises: d9feb02ebd59
Create Date: 2025-10-17 03:44:59.823301

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e76422479733"
down_revision = "6df88f451474"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "linkedin_accounts",
        sa.Column(
            "request_interval_seconds", sa.Integer(), server_default="60", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("linkedin_accounts", "request_interval_seconds")
    # ### end Alembic commands ###
