"""Create company service table

Revision ID: b545746c3cd3
Revises: 9f6c6d30835e
Create Date: 2025-04-04 07:19:36.703173

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision = "b545746c3cd3"
down_revision = "9f6c6d30835e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_services",
        sa.Column("ingest_id", sa.String(length=64), nullable=True),
        sa.Column("corporate_number", sa.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_romaji", sa.Text(), nullable=True),
        sa.Column("slug_tags", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("name_tags", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("media_code", sa.String(length=20), nullable=True),
        sa.Column("media_internal_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_romaji", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "media_code", "media_internal_id", name="company_services_unique_key"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_services")
    # ### end Alembic commands ###
