"""Alter length of career_id education_id

Revision ID: 3bb40487f18d
Revises: 12307f3e5615
Create Date: 2025-03-17 08:57:24.508508

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3bb40487f18d"
down_revision = "12307f3e5615"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "person_careers",
        "career_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "person_educations",
        "education_id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "person_educations",
        "education_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "person_careers",
        "career_id",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
