"""Change primary key on company_investor_relations

Revision ID: 797d5bdc3ae5
Revises: dbea80f0229b
Create Date: 2025-08-04 09:04:06.258125

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "797d5bdc3ae5"
down_revision = "dbea80f0229b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the table if it already exists
    op.execute("DROP TABLE IF EXISTS company_investor_relations")

    op.create_table(
        "company_investor_relations",
        sa.Column("corporate_number", sa.Text(), nullable=True),
        sa.Column("ir_id", sa.Text(), nullable=False),
        sa.Column("ir_company_name", sa.Text(), nullable=True),
        sa.Column("ir_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("ir_title", sa.Text(), nullable=True),
        sa.Column("ir_s3_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ir_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS company_investor_relations")
    # ### end Alembic commands ###
