"""add fail-reason to mail history

Revision ID: 753fa9516948
Revises: ea224c339cec
Create Date: 2025-08-27 10:12:57.378583

"""
import sqlalchemy as sa

from alembic import op
from app.models.sequence.mail_history import MAIL_HISTORY_VIEW_NAME

# revision identifiers, used by Alembic.
revision = "753fa9516948"
down_revision = "ea224c339cec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_histories", sa.Column("fail_reason", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP VIEW IF EXISTS {MAIL_HISTORY_VIEW_NAME};")
    op.drop_column("sequence_mail_histories", "fail_reason")
    # ### end Alembic commands ###
