"""add is_include_signature field in Mail template table

Revision ID: e30444e794b9
Revises: 2f2cd6538d5e
Create Date: 2025-03-21 10:19:34.864170

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e30444e794b9"
down_revision = "2f2cd6538d5e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_templates",
        sa.Column("is_include_signature", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_templates", "is_include_signature")
    # ### end Alembic commands ###
