"""create hubspot_raw_companies_unique_key

Revision ID: f9833e66b6b7
Revises: 850520214504
Create Date: 2025-02-20 07:25:17.517754

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f9833e66b6b7"
down_revision = "850520214504"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "hubspot_raw_companies_unique_key",
        "hubspot_raw_companies",
        ["hubspot_team_id", "integration_id", "hubspot_company_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "hubspot_raw_companies_unique_key", "hubspot_raw_companies", type_="unique"
    )
    # ### end Alembic commands ###
