"""empty message

Revision ID: 24d4944f17bc
Revises: af662b668940
Create Date: 2025-03-25 09:45:09.868591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24d4944f17bc'
down_revision = 'af662b668940'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mautic_event_steps', sa.Column('external_mautic_campaign_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mautic_event_steps', 'external_mautic_campaign_id')
    # ### end Alembic commands ###
