"""empty message

Revision ID: 81404e8ace8c
Revises: a0b67681316d
Create Date: 2025-06-12 08:37:57.178087

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81404e8ace8c'
down_revision = 'a0b67681316d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE source
        AS ENUM (
            'ANDIGITAL_FORM', 'DIRECTLY_REGISTER'
        );
    """
    )
    op.add_column('users', sa.Column('source', sa.Enum('ANDIGITAL_FORM', 'DIRECTLY_REGISTER', name='source'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'source')
    op.execute(
        """
        DROP TYPE source;
    """
    )
    # ### end Alembic commands ###
