"""empty message

Revision ID: 3940a83183d7
Revises: d9feb02ebd59
Create Date: 2025-10-08 03:07:59.409430

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3940a83183d7"
down_revision = "d9feb02ebd59"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_service_usage",
        sa.Column("corporate_number", sa.String(length=20), nullable=True),
        sa.Column("article_id", sa.Text(), nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("posted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("service_name", sa.Text(), nullable=True),
        sa.Column("service_url", sa.Text(), nullable=True),
        sa.Column("article_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "corporate_number",
            "article_id",
            "service_id",
            name="company_service_usage_unique",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_service_usage")
    # ### end Alembic commands ###
