"""update table hubspot

Revision ID: 9784ce12d2d9
Revises: 71a9e8176d65
Create Date: 2025-01-16 08:47:02.578991

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9784ce12d2d9"
down_revision = "71a9e8176d65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hubspot_company_not_found_pull_histories",
        sa.Column("hubspot_pull_log_id", sa.Integer(), nullable=True),
    )
    op.drop_column("hubspot_company_not_found_pull_histories", "hubspot_push_log_id")
    op.alter_column(
        "hubspot_companies",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_company_associations",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_company_custom_fields",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_company_pull_histories",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_raw_companies",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_synced_companies",
        "hubspot_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "hubspot_synced_companies",
        "ss_company_id",
        existing_type=sa.Integer(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "hubspot_manual_push_companies",
        "company_id",
        existing_type=sa.Integer(),
        type_=sa.Text(),
        nullable=True,
    )
    op.alter_column(
        "hubspot_company_push_histories",
        "ss_company_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=50),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hubspot_company_not_found_pull_histories",
        sa.Column(
            "hubspot_push_log_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("hubspot_company_not_found_pull_histories", "hubspot_pull_log_id")
    # ### end Alembic commands ###
