"""update content_items table with type of content column

Revision ID: 7a4cfe2632a9
Revises: 1019ce7d7d92
Create Date: 2025-08-14 09:10:46.420818

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a4cfe2632a9"
down_revision = "1019ce7d7d92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_step_content_items",
        "content",
        existing_type=postgresql.BYTEA(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute(
        """
        ALTER TABLE sequence_step_content_items
        ALTER COLUMN content TYPE BYTEA
        USING convert_to(content, 'UTF8')
        """
    )
    # ### end Alembic commands ###
