"""create idx corporate_number in statistic total

Revision ID: 071a4833feac
Revises: 8eae74719cb2
Create Date: 2025-05-28 09:43:50.981282

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "071a4833feac"
down_revision = "8eae74719cb2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_company_service_corporate_number",
        "company_services",
        ["corporate_number"],
        unique=False,
    )
    op.create_index(
        "idx_event_corporate_number", "events", ["corporate_number"], unique=False
    )
    op.create_index(
        "idx_person_corporate_number", "persons", ["corporate_number"], unique=False
    )
    op.create_index(
        "idx_press_release_corporate_number",
        "press_releases",
        ["corporate_number"],
        unique=False,
    )
    op.create_index(
        "idx_recruit_corporate_number", "recruits", ["corporate_number"], unique=False
    )
    op.create_index(
        "idx_technology_corporate_number",
        "technologies",
        ["corporate_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_technology_corporate_number", table_name="technologies")
    op.drop_index("idx_recruit_corporate_number", table_name="recruits")
    op.drop_index("idx_press_release_corporate_number", table_name="press_releases")
    op.drop_index("idx_person_corporate_number", table_name="persons")
    op.drop_index("idx_event_corporate_number", table_name="events")
    op.drop_index("idx_company_service_corporate_number", table_name="company_services")
    # ### end Alembic commands ###
