"""after column error message in hubspot sync table

Revision ID: dd0b85a3e80c
Revises: 40079f15f7c9
Create Date: 2025-07-30 05:02:33.590428

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dd0b85a3e80c"
down_revision = "40079f15f7c9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hubspot_company_sync_histories",
        sa.Column("error_message", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hubspot_company_sync_histories", "error_message")
    # ### end Alembic commands ###
