"""after column in salesforce integrations table

Revision ID: f797d5a10614
Revises: 3c62443e0f25
Create Date: 2025-03-21 03:36:05.174175

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f797d5a10614"
down_revision = "3c62443e0f25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesforce_integrations", sa.Column("code", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("salesforce_integrations", "code")
    # ### end Alembic commands ###
