"""Field password User null

Revision ID: ca10762b916c
Revises: 899bfba22a75
Create Date: 2025-04-01 13:00:45.294947

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca10762b916c"
down_revision = "86cf8a541e4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
