"""add event logo
Revision ID: fccd109aee98
Revises: 749b45f2d115
Create Date: 2025-04-26 15:47:28.498788
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fccd109aee98"
down_revision = "749b45f2d115"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("image", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "image")
    # ### end Alembic commands ###
