"""create company_investor_relations table

Revision ID: 3a1849fa4d63
Revises: 4fff505d69ac
Create Date: 2025-07-31 08:19:29.228187

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3a1849fa4d63"
down_revision = "4fff505d69ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_investor_relations",
        sa.Column("corporate_number", sa.Text(), nullable=True),
        sa.Column("ir_id", sa.Text(), nullable=True),
        sa.Column("ir_company_name", sa.Text(), nullable=True),
        sa.Column("ir_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("ir_title", sa.Text(), nullable=True),
        sa.Column("ir_s3_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS company_investor_relations")
    # ### end Alembic commands ###
