"""update sequence_step_content_item_with_mime_type

Revision ID: 295f6fd9d018
Revises: 102f8066f222
Create Date: 2025-08-02 04:09:05.108433

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "295f6fd9d018"
down_revision = "102f8066f222"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_step_content_items",
        sa.Column("mime_type", sa.String(length=64), nullable=True),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_step_content_items", "mime_type")
    # ### end Alembic commands ###
