"""change type value column salesforce team id

Revision ID: a5c33749c6c1
Revises: 606c4c5eac69
Create Date: 2025-03-24 07:51:38.362832

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a5c33749c6c1"
down_revision = "606c4c5eac69"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_company_field_mappings",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_company_pull_histories",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_company_push_histories",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_custom_field_settings",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_integrations",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_raw_companies",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_raw_persons",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_sync_histories",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    op.alter_column(
        "salesforce_synced_companies",
        "salesforce_team_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_company_field_mappings",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_company_pull_histories",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_company_push_histories",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_custom_field_settings",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_integrations",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_raw_companies",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_raw_persons",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_sync_histories",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "salesforce_synced_companies",
        "salesforce_team_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    # ### end Alembic commands ###
