"""init_sequence_tasks_table

Revision ID: 8489f9f67031
Revises: dcbc990a5308
Create Date: 2025-02-18 06:26:12.538502

"""
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

from alembic import op

# revision identifiers, used by Alembic.
revision = "8489f9f67031"
down_revision = "05bc7ff99aa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequence_tasks",
        sa.Column("sequence_person_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("sequence_campaign_id", sa.Integer(), nullable=True),
        sa.Column("sequence_step_id", sa.Integer(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum("EMAIL", "CALL", "ACTION_ITEM", name="tasktype"),
            nullable=True,
        ),
        sa.Column(
            "priority",
            ENUM("LOW", "MEDIUM", "HIGH", name="priority", create_type=False),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=128), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("due_date", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "COMPLTETED", "ARCHIVED", name="taskstatus"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence_tasks")
    op.execute("DROP TYPE IF EXISTS tasktype, taskstatus")
    # ### end Alembic commands ###
