"""empty message

Revision ID: 0a2f7d428e48
Revises: 262806f003ae
Create Date: 2025-07-01 08:24:33.689337

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a2f7d428e48"
down_revision = "262806f003ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_campaigns",
        sa.Column(
            "is_first_active",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_campaigns", "is_first_active")
    # ### end Alembic commands ###
