"""Add role_group column to person table

Revision ID: 12307f3e5615
Revises: 40d06688a796
Create Date: 2025-03-17 06:49:56.468211

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "12307f3e5615"
down_revision = "40d06688a796"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("role_group", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "role_group")
    # ### end Alembic commands ###
