"""add google token field in mailbox table

Revision ID: 426bddc02b5d
Revises: d45eb291d589
Create Date: 2025-03-11 08:11:53.942049

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "426bddc02b5d"
down_revision = "599eee8b7d2b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mailboxes",
        sa.Column("google_refresh_token", sa.Text(), nullable=True),
    )
    op.execute(
        """
        CREATE TYPE mailboxtype
        AS ENUM (
            'SMTP',
            'GOOGLE_API'
        );
        """
    )
    op.add_column(
        "sequence_mailboxes",
        sa.Column(
            "mailbox_type",
            sa.Enum("SMTP", "GOOGLE_API", name="mailboxtype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mailboxes", "mailbox_type")
    op.drop_column("sequence_mailboxes", "google_refresh_token")
    # ### end Alembic commands ###
