"""update_sequence_campaign_contacts_with_time_resumed

Revision ID: 4ed53b0320c7
Revises: 1455db1ba8f0
Create Date: 2025-09-03 02:16:17.581378

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4ed53b0320c7"
down_revision = "1455db1ba8f0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_campaign_contacts",
        "time_resumed",
        existing_type=sa.TIMESTAMP(),
        server_default=None,
        existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_campaign_contacts",
        "time_resumed",
        existing_type=sa.TIMESTAMP(),
        server_default=sa.text("now()")
    )
    # ### end Alembic commands ###
