"""update linkedin activities table with enum and excutor option

Revision ID: 97582576a957
Revises: 4fd0fb9680d6
Create Date: 2025-08-07 01:50:03.674703

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "97582576a957"
down_revision = "797d5bdc3ae5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # If you want to add new enum column in existed table, you must create new enum type first
    op.execute(
        "CREATE TYPE executoroption AS ENUM ('CURRENT_STEP', 'ALL_FOLLOWING_STEPS')"
    )

    op.add_column(
        "sequence_linkedin_activities",
        sa.Column(
            "executor_option",
            sa.Enum("CURRENT_STEP", "ALL_FOLLOWING_STEPS", name="executoroption"),
            nullable=True,
        ),
    )

    # update enum
    # Step 1: Drop default constraints (if any), or cast columns
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN status DROP DEFAULT"
    )
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN process_status DROP DEFAULT"
    )

    # Step 2: Cast columns to TEXT (temporary)
    op.execute("ALTER TABLE sequence_linkedin_activities ALTER COLUMN status TYPE TEXT")
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN process_status TYPE TEXT"
    )

    # Step 3: Drop old enum types
    op.execute("DROP TYPE IF EXISTS linkedinhistorystatus")
    op.execute("DROP TYPE IF EXISTS linkedinhistoryprocessstatus")

    # Step 4: Recreate enum types with new values
    op.execute(
        "CREATE TYPE linkedinhistorystatus AS ENUM ('SENT', 'FAILED', 'SKIPPED', 'SCHEDULED', 'OPENED', 'DRAFT', 'REPLIED', 'BOUNCED', 'OPT_OUT')"
    )
    op.execute(
        "CREATE TYPE linkedinhistoryprocessstatus AS ENUM ('PENDING', 'PERSON_PAUSED', 'LINKEDIN_ACCOUNT_NOT_FOUND', 'SUCCESS', 'FAILED')"
    )

    # Step 5: Alter columns back to new enum type
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN status TYPE linkedinhistorystatus USING status::linkedinhistorystatus"
    )
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN process_status TYPE linkedinhistoryprocessstatus USING process_status::linkedinhistoryprocessstatus"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_linkedin_activities", "executor_option")
    op.execute("DROP TYPE IF EXISTS executoroption")

    # downgrade enum
    # Optional: reverse the steps if needed
    op.execute("ALTER TABLE sequence_linkedin_activities ALTER COLUMN status TYPE TEXT")
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN process_status TYPE TEXT"
    )

    op.execute("DROP TYPE IF EXISTS linkedinhistorystatus")
    op.execute("DROP TYPE IF EXISTS linkedinhistoryprocessstatus")

    op.execute(
        "CREATE TYPE linkedinhistorystatus AS ENUM ('SENT', 'FAILED', 'SKIPPED', 'SCHEDULED', 'REPLIED')"
    )
    op.execute(
        "CREATE TYPE linkedinhistoryprocessstatus AS ENUM ('PENDING', 'PERSON_PAUSED', 'SUCCESS', 'FAILED')"
    )

    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN status TYPE linkedinhistorystatus USING status::linkedinhistorystatus"
    )
    op.execute(
        "ALTER TABLE sequence_linkedin_activities ALTER COLUMN process_status TYPE linkedinhistoryprocessstatus USING process_status::linkedinhistoryprocessstatus"
    )

    # ### end Alembic commands ###
