"""update_sequence_tasks_with_linkedin

Revision ID: 07052f87260c
Revises: 83a5052c6ac2
Create Date: 2025-09-29 04:54:18.195038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "07052f87260c"
down_revision = "83a5052c6ac2"
branch_labels = None
depends_on = None

# Khai báo enum một lần
account_option_enum = postgresql.ENUM(
    "MANUAL", "DEFAULT", name="accountoption"
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    account_option_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "sequence_tasks",
        sa.Column("sequence_linkedin_account_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "sequence_tasks",
        sa.Column(
            "account_option",
            sa.Enum("MANUAL", "DEFAULT", name="accountoption"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_tasks", "account_option")
    op.drop_column("sequence_tasks", "sequence_linkedin_account_id")
    # ### end Alembic commands ###
