"""after column total companies in hubspot sync table

Revision ID: 40079f15f7c9
Revises: cf45f4864d01
Create Date: 2025-07-30 03:44:51.563292

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "40079f15f7c9"
down_revision = "cf45f4864d01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hubspot_company_sync_histories",
        sa.Column("total_companies", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hubspot_company_sync_histories", "total_companies")
    # ### end Alembic commands ###
