"""empty message

Revision ID: 74c7d1b9aa75
Revises: 9e24f4c3f9f2
Create Date: 2025-04-10 08:02:45.199972

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74c7d1b9aa75'
down_revision = '9e24f4c3f9f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_mail_alias_settings',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('mailbox_id', sa.Integer(), nullable=True),
    sa.Column('mailbox_alias_id', sa.Integer(), nullable=True),
    sa.Column('setting_option', sa.Enum('CONTACT', 'STEP', name='settingoption'), nullable=True),
    sa.Column('sequence_person_id', sa.Integer(), nullable=True),
    sa.Column('sequence_campaign_id', sa.Integer(), nullable=True),
    sa.Column('sequence_step_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_unsubcriptions',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('email_from', sa.String(length=255), nullable=True),
    sa.Column('email_to', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sequence_mail_histories', sa.Column('mailbox_alias_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mail_histories', 'mailbox_alias_id')
    op.drop_table('sequence_unsubcriptions')
    op.drop_table('sequence_mail_alias_settings')
    # ### end Alembic commands ###
