"""change type list matched_company_id

Revision ID: 39fae504e3a7
Revises: 6f941ccd12c8
Create Date: 2025-04-26 10:09:50.062484

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "39fae504e3a7"
down_revision = "6f941ccd12c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_person_multiple_pull_histories",
        "matched_company_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_person_multiple_pull_histories",
        "matched_company_ids",
        existing_type=sa.ARRAY(sa.Text()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
