"""add company service cols

Revision ID: 777817de1e84
Revises: 3312bc8c1955
Create Date: 2025-09-05 02:42:35.422575

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "777817de1e84"
down_revision = "3312bc8c1955"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("company_services", sa.Column("category", sa.Text(), nullable=True))
    op.add_column(
        "company_services", sa.Column("sub_category", sa.Text(), nullable=True)
    )
    op.add_column("company_services", sa.Column("score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company_services", "score")
    op.drop_column("company_services", "sub_category")
    op.drop_column("company_services", "category")
    # ### end Alembic commands ###
