"""after column id_url in salesforce integration

Revision ID: e93d5fa5661b
Revises: 162957721983
Create Date: 2025-05-15 07:49:35.968416

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e93d5fa5661b"
down_revision = "162957721983"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesforce_integrations", sa.Column("id_url", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("salesforce_integrations", "id_url")
    # ### end Alembic commands ###
