"""after table salesforce integrations

Revision ID: 3c62443e0f25
Revises: 3bb40487f18d
Create Date: 2025-03-20 09:38:12.793336

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3c62443e0f25"
down_revision = "3bb40487f18d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesforce_company_field_mappings",
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_field", sa.String(length=255), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column(
            "field_class",
            sa.Enum("PREDEFINED", "CUSTOM", name="field_class_mapping_enum"),
            nullable=True,
        ),
        sa.Column("overwrite_flag", sa.Boolean(), nullable=True),
        sa.Column("autofill_flag", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_multiple_pull_histories",
        sa.Column("salesforce_pull_history_id", sa.Integer(), nullable=True),
        sa.Column(
            "matched_company_ids", sa.ARRAY(sa.String(length=255)), nullable=True
        ),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_multiple_push_histories",
        sa.Column("salesforce_push_history_id", sa.Integer(), nullable=True),
        sa.Column("matched_company_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_not_found_pull_histories",
        sa.Column("salesforce_pull_history_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_not_found_push_histories",
        sa.Column("salesforce_push_history_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_pull_histories",
        sa.Column("salesforce_company_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("log_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_company_push_histories",
        sa.Column("ss_company_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("log_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_custom_field_settings",
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("object_type", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_integrations",
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_manual_push_companies",
        sa.Column("ss_company_id", sa.Integer(), nullable=True),
        sa.Column("log_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_person_multiple_pull_histories",
        sa.Column("salesforce_person_history_id", sa.Integer(), nullable=True),
        sa.Column("matched_company_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_person_not_found_pull_histories",
        sa.Column("salesforce_person_history_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_person_pull_histories",
        sa.Column("salesforce_person_id", sa.String(length=50), nullable=True),
        sa.Column("salesforce_company_id", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=50), nullable=True),
        sa.Column("log_id", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_raw_companies",
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_comapny_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "salesforce_team_id",
            "salesforce_integration_id",
            "salesforce_comapny_id",
            name="salesforce_raw_companies_unique_key",
        ),
    )
    op.create_table(
        "salesforce_raw_persons",
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_person_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "salesforce_team_id",
            "salesforce_integration_id",
            "salesforce_person_id",
            name="salesforce_raw_persons_unique_key",
        ),
    )
    op.create_table(
        "salesforce_sync_histories",
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "SYNC_COMPANIES",
                "PULL_COMPANIES",
                "PUSH_COMPANIES",
                "PULL_PERSONS",
                name="type_integration_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "method",
            sa.Enum("MANUAL", "AUTO", name="method_integration_enum"),
            nullable=True,
        ),
        sa.Column("log_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salesforce_synced_companies",
        sa.Column("ss_company_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_integration_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_team_id", sa.Integer(), nullable=True),
        sa.Column("salesforce_comapny_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salesforce_synced_companies")
    op.drop_table("salesforce_sync_histories")
    op.drop_table("salesforce_raw_persons")
    op.drop_table("salesforce_raw_companies")
    op.drop_table("salesforce_person_pull_histories")
    op.drop_table("salesforce_person_not_found_pull_histories")
    op.drop_table("salesforce_person_multiple_pull_histories")
    op.drop_table("salesforce_manual_push_companies")
    op.drop_table("salesforce_integrations")
    op.drop_table("salesforce_custom_field_settings")
    op.drop_table("salesforce_company_push_histories")
    op.drop_table("salesforce_company_pull_histories")
    op.drop_table("salesforce_company_not_found_push_histories")
    op.drop_table("salesforce_company_not_found_pull_histories")
    op.drop_table("salesforce_company_multiple_push_histories")
    op.drop_table("salesforce_company_multiple_pull_histories")
    op.drop_table("salesforce_company_field_mappings")
    # ### end Alembic commands ###
