"""edit plan and credit

Revision ID: a30bdf1754cc
Revises: b3870127dfbe
Create Date: 2025-04-09 09:57:53.778435

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "a30bdf1754cc"
down_revision = "74c7d1b9aa75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("plans", sa.Column("unlock_cpn_quota", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("send_form_quota", sa.Integer(), nullable=True))
    op.add_column(
        "plans", sa.Column("unlock_person_quota", sa.Integer(), nullable=True)
    )
    op.add_column("plans", sa.Column("send_email_quota", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("download_csv_quota", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("telesale_quota", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("price", sa.Integer(), nullable=True))
    op.add_column("plans", sa.Column("contract_month", sa.Integer(), nullable=True))
    op.alter_column(
        "plans",
        "name_code",
        existing_type=postgresql.ENUM(
            "PRE", "ADV", "STD", "SML", "FRE", name="plancode"
        ),
        type_=postgresql.ENUM(
            "FRE",
            "MICRO",
            "SML",
            "STD",
            "PRE",
            "UNLIMITED",
            "CUSTOMIZE",
            name="plancode",
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "service_code",
        existing_type=postgresql.ENUM("LISTING", "FORM", name="plan_service_code"),
        type_=postgresql.ENUM(
            "LISTING",
            "CPN",
            "PERSON",
            "MSG",
            "FORM",
            "EMAIL",
            "CSV",
            "TELESALE",
            name="plan_service_code",
        ),
        existing_nullable=True,
    )
    op.drop_column("plans", "download_cpn_quota")
    op.drop_column("plans", "ctf_quota")
    op.add_column("subcriptions", sa.Column("start_at", sa.TIMESTAMP(), nullable=True))
    op.add_column(
        "subcriptions",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
    )
    op.alter_column(
        "subcriptions",
        "service_code",
        existing_type=postgresql.ENUM("LISTING", "FORM", name="plan_service_code"),
        type_=postgresql.ENUM(
            "LISTING",
            "CPN",
            "PERSON",
            "MSG",
            "FORM",
            "EMAIL",
            "CSV",
            "TELESALE",
            name="plan_service_code",
        ),
        existing_nullable=True,
    )

    op.add_column("team_credits", sa.Column("used_amount", sa.Integer(), nullable=True))
    op.add_column(
        "team_credits",
        sa.Column(
            "plan_code",
            sa.Enum(
                "FRE",
                "MICRO",
                "SML",
                "STD",
                "PRE",
                "UNLIMITED",
                "CUSTOMIZE",
                name="plancode",
            ),
            nullable=True,
        ),
    )
    op.add_column("team_credits", sa.Column("start_at", sa.TIMESTAMP(), nullable=True))
    op.add_column("team_credits", sa.Column("end_at", sa.TIMESTAMP(), nullable=True))
    op.add_column(
        "team_credits",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_credits", "is_active")
    op.drop_column("team_credits", "plan_code")
    op.drop_column("team_credits", "end_at")
    op.drop_column("team_credits", "start_at")
    op.drop_column("team_credits", "used_amount")
    op.alter_column(
        "subcriptions",
        "service_code",
        existing_type=postgresql.ENUM(
            "LISTING",
            "CPN",
            "PERSON",
            "MSG",
            "FORM",
            "EMAIL",
            "CSV",
            "TELESALE",
            name="plan_service_code",
        ),
        type_=postgresql.ENUM("LISTING", "FORM", name="plan_service_code"),
        existing_nullable=True,
    )
    op.drop_column("subcriptions", "is_active")
    op.drop_column("subcriptions", "start_at")
    op.add_column(
        "plans",
        sa.Column("ctf_quota", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "plans",
        sa.Column(
            "download_cpn_quota", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "plans",
        "service_code",
        existing_type=postgresql.ENUM(
            "LISTING",
            "CPN",
            "PERSON",
            "MSG",
            "FORM",
            "EMAIL",
            "CSV",
            "TELESALE",
            name="plan_service_code",
        ),
        type_=postgresql.ENUM("LISTING", "FORM", name="plan_service_code"),
        existing_nullable=True,
    )
    op.alter_column(
        "plans",
        "name_code",
        existing_type=sa.String(length=20),
        type_=postgresql.ENUM("PRE", "ADV", "STD", "SML", "FRE", name="plancode"),
        existing_nullable=True,
    )
    op.drop_column("plans", "contract_month")
    op.drop_column("plans", "price")
    op.drop_column("plans", "telesale_quota")
    op.drop_column("plans", "download_csv_quota")
    op.drop_column("plans", "send_email_quota")
    op.drop_column("plans", "unlock_person_quota")
    op.drop_column("plans", "send_form_quota")
    op.drop_column("plans", "unlock_cpn_quota")

    # ### end Alembic commands ###
