"""create_hubspot_person_not_found_company

Revision ID: 90f5e9c1cd85
Revises: aae9e639bd71
Create Date: 2025-01-21 10:43:23.924104

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "90f5e9c1cd85"
down_revision = "aae9e639bd71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hubspot_person_not_found_hubspot_company_histories",
        sa.Column("hubspot_person_log_id", sa.Integer(), nullable=True),
        sa.Column("ss_company_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hubspot_person_not_found_hubspot_company_histories")
    # ### end Alembic commands ###
