"""add enum for bounce type and subtype

Revision ID: 03edb9491ed8
Revises: 9584e7b2547f
Create Date: 2025-03-28 08:03:28.169962

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "03edb9491ed8"
down_revision = "9584e7b2547f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE mailhistorybouncetype AS ENUM ('PERMANENT', 'TRANSIENT', 'UNDETERMINED');
        CREATE TYPE mailhistorybouncesubtype AS ENUM (
            'GENERAL',
            'NO_EMAIL',
            'SUPPRESSED',
            'ON_ACCOUNT_SUPPRESSION_LIST',
            'MESSAGE_TOO_LARGE',
            'MAILBOX_FULL',
            'CONTENT_REJECTED',
            'ATTACHMENT_REJECTED',
            'UNDETERMINED'
        )
    """
    )
    op.execute(
        """
        ALTER TABLE sequence_mail_histories
        ALTER COLUMN bounce_type
        TYPE mailhistorybouncetype
        USING bounce_type::mailhistorybouncetype
    """
    )
    op.execute(
        """
        ALTER TABLE sequence_mail_histories
        ALTER COLUMN bounce_sub_type
        TYPE mailhistorybouncesubtype
        USING bounce_sub_type::mailhistorybouncesubtype
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_mail_histories",
        "bounce_sub_type",
        existing_type=sa.Enum(
            "GENERAL",
            "NO_EMAIL",
            "SUPPRESSED",
            "ON_ACCOUNT_SUPPRESSION_LIST",
            "MESSAGE_TOO_LARGE",
            "MAILBOX_FULL",
            "CONTENT_REJECTED",
            "ATTACHMENT_REJECTED",
            "UNDETERMINED",
            name="mailhistorybouncesubtype",
        ),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "sequence_mail_histories",
        "bounce_type",
        existing_type=sa.Enum(
            "PERMANENT", "TRANSIENT", "UNDETERMINED", name="mailhistorybouncetype"
        ),
        type_=sa.VARCHAR(length=64),
        existing_nullable=True,
    )
    op.execute("DROP TYPE mailhistorybouncesubtype; DROP TYPE mailhistorybouncetype;")
    # ### end Alembic commands ###
