"""creat team_invitation table

Revision ID: 48d40daaffcc
Revises: 0ce1b1f55bdf
Create Date: 2025-07-10 09:51:08.373869

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "48d40daaffcc"
down_revision = "2bb1c176628a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_invitations",
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("inviter_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("token", sa.String(length=255), nullable=True),
        sa.Column("accepted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("rejected_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_invitations")
    # ### end Alembic commands ###
