"""add is_include_opt_out_and_signature only

Revision ID: a1b2c3d4e5f6
Revises: fcbcaa9620cc
Create Date: 2025-06-25 05:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f6"
down_revision = "3b002e946611"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mail_histories', sa.Column('is_include_opt_out_and_signature', sa.Boolean(), nullable=True, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mail_histories', 'is_include_opt_out_and_signature')
    # ### end Alembic commands ### 