"""empty message

Revision ID: 04e7948ea4aa
Revises: 6307b2c762b3
Create Date: 2025-02-18 06:16:20.415263

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e7948ea4aa'
down_revision = '6307b2c762b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies_custom',
    sa.Column('company_custom_id', sa.String(length=64), nullable=True),
    sa.Column('establish_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('kana_name', sa.Text(), nullable=True),
    sa.Column('english_name', sa.Text(), nullable=True),
    sa.Column('normalized_name', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('nta_city_id', sa.Integer(), nullable=True),
    sa.Column('nta_prefecture_id', sa.Integer(), nullable=True),
    sa.Column('corporate_number', sa.Text(), nullable=True),
    sa.Column('corporate_kind', sa.SmallInteger(), nullable=True),
    sa.Column('nta_closed_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('nta_closed_reason', sa.Text(), nullable=True),
    sa.Column('nta_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('nta_created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('president_name', sa.Text(), nullable=True),
    sa.Column('president_dob', sa.TIMESTAMP(), nullable=True),
    sa.Column('factories_count', sa.Integer(), nullable=True),
    sa.Column('branches_count', sa.Integer(), nullable=True),
    sa.Column('headquarters_count', sa.Integer(), nullable=True),
    sa.Column('industry_code', sa.String(length=255), nullable=True),
    sa.Column('business_content', sa.Text(), nullable=True),
    sa.Column('listing_market_code', sa.String(length=255), nullable=True),
    sa.Column('listing_year', sa.Integer(), nullable=True),
    sa.Column('revenue_change', sa.Integer(), nullable=True),
    sa.Column('employee_change', sa.Integer(), nullable=True),
    sa.Column('revenue_change_rate', sa.Float(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('twitter_url', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('contact_form_url', sa.Text(), nullable=True),
    sa.Column('president_university', sa.Text(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('recruit_phone', sa.Text(), nullable=True),
    sa.Column('sub_companies_count', sa.Integer(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('recruit_email', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.Text(), nullable=True),
    sa.Column('capital_adequacy_ratio', sa.Float(), nullable=True),
    sa.Column('capital', sa.BigInteger(), nullable=True),
    sa.Column('capital_change', sa.Integer(), nullable=True),
    sa.Column('average_work_duration', sa.Float(), nullable=True),
    sa.Column('fax', sa.Text(), nullable=True),
    sa.Column('closing_month', sa.SmallInteger(), nullable=True),
    sa.Column('employee_change_rate', sa.Float(), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('average_age', sa.Float(), nullable=True),
    sa.Column('average_salary', sa.Integer(), nullable=True),
    sa.Column('latest_recruits_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('this_month_recruits_count', sa.Integer(), nullable=True),
    sa.Column('this_month_doda_recruits_count', sa.Integer(), nullable=True),
    sa.Column('this_month_mynavi_tenshoku_recruits_count', sa.Integer(), nullable=True),
    sa.Column('latest_press_release_at', sa.Integer(), nullable=True),
    sa.Column('this_month_prtimes_count', sa.Integer(), nullable=True),
    sa.Column('this_month_value_press_count', sa.Integer(), nullable=True),
    sa.Column('display_flag', sa.SmallInteger(), nullable=True),
    sa.Column('meta_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('main_sub_industry_code', sa.String(length=255), nullable=True),
    sa.Column('sub_industries_code', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('revenue_raw', sa.Text(), nullable=True),
    sa.Column('capital_raw', sa.Text(), nullable=True),
    sa.Column('tool_codes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('one_month_employee_delta', sa.Integer(), nullable=True),
    sa.Column('three_month_employee_delta', sa.Integer(), nullable=True),
    sa.Column('six_month_employee_delta', sa.Integer(), nullable=True),
    sa.Column('one_year_employee_delta', sa.Integer(), nullable=True),
    sa.Column('one_month_capital_delta', sa.BigInteger(), nullable=True),
    sa.Column('three_month_capital_delta', sa.BigInteger(), nullable=True),
    sa.Column('six_month_capital_delta', sa.BigInteger(), nullable=True),
    sa.Column('one_year_capital_delta', sa.BigInteger(), nullable=True),
    sa.Column('one_month_revenue_delta', sa.BigInteger(), nullable=True),
    sa.Column('three_month_revenue_delta', sa.BigInteger(), nullable=True),
    sa.Column('six_month_revenue_delta', sa.BigInteger(), nullable=True),
    sa.Column('one_year_revenue_delta', sa.BigInteger(), nullable=True),
    sa.Column('latest_new_graduate_recruit_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('press_release_media_codes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('recruit_media_codes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('occupation_codes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('raw_occupations', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('skill_codes', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('group_employee_count', sa.Integer(), nullable=True),
    sa.Column('main_customers', sa.Text(), nullable=True),
    sa.Column('group_companies', sa.Text(), nullable=True),
    sa.Column('market_capitalization_raw', sa.Text(), nullable=True),
    sa.Column('market_capitalization', sa.BigInteger(), nullable=True),
    sa.Column('address_latitude', sa.BigInteger(), nullable=True),
    sa.Column('address_longitude', sa.BigInteger(), nullable=True),
    sa.Column('recruit_tags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('recruit_qualifications', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('tech_languages', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('tech_frameworks', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('tech_clouds', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('tech_databases', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('communication_tools', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('management_tools', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('internal_tools', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('crm_tools', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('business_model_codes', sa.ARRAY(sa.String(length=10)), nullable=True),
    sa.Column('display_ng_flag', sa.Boolean(), nullable=True),
    sa.Column('contact_ng_flag', sa.Boolean(), nullable=True),
    sa.Column('contact_info_ng_flag', sa.Boolean(), nullable=True),
    sa.Column('contact_sales_ng_flag', sa.Boolean(), nullable=True),
    sa.Column('three_month_funding_flags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('six_month_funding_flags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('twelve_month_funding_flags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('all_funding_flags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('establish_time_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hp_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('listing_time_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_custom_id', name='companies_company_custom_id_unique'),
    )
    op.create_index(op.f('ix_companies_custom_normalized_name'), 'companies_custom', ['normalized_name'], unique=False)
    op.add_column('company_collection_items', sa.Column('company_custom_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_collection_items', 'company_custom_id')
    op.drop_index(op.f('ix_companies_custom_normalized_name'), table_name='companies_custom')
    op.drop_table('companies_custom')
    # ### end Alembic commands ###
