"""empty message

Revision ID: 21c64c88e5e5
Revises: 777817de1e84
Create Date: 2025-09-10 11:17:09.248624

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "21c64c88e5e5"
down_revision = "753fa9516948"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("reset_password_at", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "reset_password_at")
    # ### end Alembic commands ###
