"""Add column flag-first-login

Revision ID: 8955fa641c8d
Revises: 45e6eb3cc360
Create Date: 2025-04-03 05:45:35.986731

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8955fa641c8d"
down_revision = "ca10762b916c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("flag_first_login", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "flag_first_login")
    # ### end Alembic commands ###
