"""set_sequence_person_stage_to_enum

Revision ID: f945a40b8ea0
Revises: 786b05eb1289
Create Date: 2025-02-24 07:29:37.345549

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "f945a40b8ea0"
down_revision = "786b05eb1289"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE sequencepersonstage
        AS ENUM (
            'COLD',
            'APPROACHING',
            'BAD_DATA',
            'DO_NOT_CONTACT',
            'REPLIED',
            'UNRESPONSIVE'
        );
    """
    )
    op.execute(
        """
        ALTER TABLE sequence_persons
        ALTER COLUMN stage TYPE sequencepersonstage
        USING stage::sequencepersonstage;
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS sequencepersonstage;")
    # ### end Alembic commands ###
