"""change type value matched company ids in salesforce

Revision ID: 03a370ae3107
Revises: 46ae6a64fc50
Create Date: 2025-07-03 09:55:23.494222

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "03a370ae3107"
down_revision = "38fb1c4b26ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_company_multiple_push_histories",
        "matched_company_ids",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "salesforce_company_multiple_push_histories",
        "matched_company_ids",
        existing_type=sa.ARRAY(sa.Text()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
