"""add fields to mail history table

Revision ID: 9584e7b2547f
Revises: af662b668940
Create Date: 2025-03-25 10:47:29.240058

"""
import sqlalchemy as sa

from alembic import op
from app.models.sequence.mail_history import MAIL_HISTORY_VIEW_NAME

# revision identifiers, used by Alembic.
revision = "9584e7b2547f"
down_revision = "78b8288fedbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_histories",
        sa.Column("thread_id", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("delivered_at", sa.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories", sa.Column("opened_at", sa.TIMESTAMP(), nullable=True)
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("replied_at", sa.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("bounced_at", sa.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("bounce_type", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("bounce_sub_type", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column("diag_code", sa.String(length=255), nullable=True),
    )
    op.execute("ALTER TYPE mailhistorystatus ADD VALUE 'BOUNCED';")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
        DROP VIEW {MAIL_HISTORY_VIEW_NAME};
        UPDATE sequence_mail_histories set status=NULL WHERE status = 'BOUNCED';
        CREATE TYPE status_enum_new AS ENUM ('SENT', 'FAILED', 'SKIPPED', 'SCHEDULED', 'OPENED', 'DRAFT', 'REPLIED');
        ALTER TABLE sequence_mail_histories
        ALTER COLUMN status TYPE status_enum_new
        USING status::text::status_enum_new;
        DROP TYPE mailhistorystatus;
        ALTER TYPE status_enum_new RENAME TO mailhistorystatus;
    """
    )
    op.drop_column("sequence_mail_histories", "diag_code")
    op.drop_column("sequence_mail_histories", "bounce_sub_type")
    op.drop_column("sequence_mail_histories", "bounce_type")
    op.drop_column("sequence_mail_histories", "bounced_at")
    op.drop_column("sequence_mail_histories", "replied_at")
    op.drop_column("sequence_mail_histories", "opened_at")
    op.drop_column("sequence_mail_histories", "delivered_at")
    op.drop_column("sequence_mail_histories", "thread_id")
    op.execute(
        f"""
        CREATE VIEW {MAIL_HISTORY_VIEW_NAME} AS (
        SELECT
            smh.sequence_person_id,
            sp."name" AS sequence_person_name,
            smh.sequence_campaign_id,
            sc."name" AS sequence_campaign_name,
            smh.sequence_step_id,
            scs."order" AS sequence_step_order,
            smh.sequence_mailbox_id,
            sm.email AS email_from,
            smh.title,
            smh."content",
            smh.email_to,
            smh.status,
            smh.sent_at,
            smh.sent_by,
            u."name" AS sender_name,
            'HISTORY' AS mail_history_type
        FROM
            sequence_mail_histories smh
            JOIN sequence_campaign_steps scs ON smh.sequence_step_id = scs.id
            JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
            JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
            JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
            JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
            JOIN users u ON smh.sent_by = u.id
        WHERE
            smh.deleted_at IS NULL
        UNION
        SELECT
            tmp.sequence_person_id,
            tmp.sequence_person_name,
            tmp.sequence_campaign_id,
            tmp.sequence_campaign_name,
            tmp.next_sequence_step_id AS sequence_step_id,
            tmp.sequence_step_order,
            tmp.sequence_mailbox_id,
            tmp.email_from,
            tmp.mail_template_title AS title,
            tmp.mail_template_content AS content,
            tmp.email_to,
            'SCHEDULED' AS status,
            CASE
                WHEN tmp.timing_type = 'SCHEDULED' AND tmp.step_type = 'MAIL_AUTO' THEN tmp.sent_at + (tmp.schedule_value || ' ' || tmp.schedule_unit)::interval
            END AS sent_at,
            tmp.sent_by,
            tmp.sender_name,
            'FUTURE' AS mail_history_type
        FROM
            (
                SELECT
                    smh.*,
                    scs.timing_type,
                    scs.schedule_unit,
                    scs.schedule_value,
                    scs.step_type,
                    sp.name AS sequence_person_name,
                    sc.name AS sequence_campaign_name,
                    scs."order" AS sequence_step_order,
                    sm.email AS email_from,
                    smt.title AS mail_template_title,
                    u."name" AS sender_name,
                    smt."content" AS mail_template_content,
                    ROW_NUMBER() OVER (
                        PARTITION BY
                            smh.sequence_campaign_id,
                            smh.sequence_person_id
                        ORDER BY
                            scs.order DESC
                    ) AS row_num
                FROM
                    sequence_mail_histories smh
                    JOIN sequence_campaign_steps scs ON smh.next_sequence_step_id = scs.id
                    JOIN sequence_mail_templates smt ON scs.mail_template_id = smt.id
                    JOIN sequence_campaigns sc ON smh.sequence_campaign_id = sc.id
                    JOIN sequence_mailboxes sm ON smh.sequence_mailbox_id = sm.id
                    JOIN sequence_persons sp ON smh.sequence_person_id = sp.id
                    JOIN users u ON smh.sent_by = u.id
            ) tmp
        WHERE
            tmp.row_num = 1
            AND tmp.status != 'SCHEDULED'
            AND tmp.deleted_at is NULL
    );
    """
    )
    # ### end Alembic commands ###
