"""empty message

Revision ID: d45eb291d589
Revises: 77bf794d6ba0
Create Date: 2025-02-27 03:21:21.207147

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd45eb291d589'
down_revision = '77bf794d6ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mautic_campaigns', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('sequence_mautic_segments', sa.Column('external_mautic_campaign_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mautic_segments', 'external_mautic_campaign_id')
    op.drop_column('sequence_mautic_campaigns', 'order')
    # ### end Alembic commands ###
