"""after column check run auto batch

Revision ID: 1019ce7d7d92
Revises: 3b76cb0303e0
Create Date: 2025-08-13 06:51:53.617365

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1019ce7d7d92"
down_revision = "3b76cb0303e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hubspot_integrations",
        sa.Column("auto_pull_companies", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "hubspot_integrations",
        sa.Column("auto_pull_persons", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "hubspot_integrations",
        sa.Column("auto_sync_companies", sa.Boolean(), nullable=True),
    )
    op.drop_column("hubspot_integrations", "company_merge_strategy")
    op.drop_column("hubspot_integrations", "person_merge_strategy")
    op.add_column(
        "salesforce_integrations",
        sa.Column("auto_pull_companies", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "salesforce_integrations",
        sa.Column("auto_pull_persons", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "salesforce_integrations",
        sa.Column("auto_sync_companies", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("salesforce_integrations", "auto_sync_companies")
    op.drop_column("salesforce_integrations", "auto_pull_persons")
    op.drop_column("salesforce_integrations", "auto_pull_companies")
    op.add_column(
        "hubspot_integrations",
        sa.Column(
            "person_merge_strategy",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "hubspot_integrations",
        sa.Column(
            "company_merge_strategy",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("hubspot_integrations", "auto_sync_companies")
    op.drop_column("hubspot_integrations", "auto_pull_persons")
    op.drop_column("hubspot_integrations", "auto_pull_companies")
    # ### end Alembic commands ###
