"""empty message

Revision ID: 04cae02bd2a1
Revises: 04b04c1bc0e6
Create Date: 2025-06-05 04:37:27.333098

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "04cae02bd2a1"
down_revision = "04b04c1bc0e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TYPE mailhistorystatus ADD VALUE 'OPT_OUT'
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
