"""change value form job status code

Revision ID: 3b002e946611
Revises: ec1bb80a26d9
Create Date: 2025-06-23 07:29:18.307378

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b002e946611"
down_revision = "ec1bb80a26d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE form_job_status_code RENAME VALUE 'RUNNING_SUCCESS' TO 'RUNNING'"
    )
    op.execute("ALTER TYPE form_job_status_code RENAME VALUE 'DONE_SUCCESS' TO 'DONE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE form_job_status_code RENAME VALUE 'DONE' TO 'DONE_SUCCESS'")
    op.execute(
        "ALTER TYPE form_job_status_code RENAME VALUE 'RUNNING' TO 'RUNNING_SUCCESS'"
    )
    # ### end Alembic commands ###
