"""add column team_member_role_code in users table

Revision ID: 9b1276e8a7e9
Revises: 8ec0cbbcb1f1
Create Date: 2025-07-09 06:31:09.390729

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b1276e8a7e9"
down_revision = "8ec0cbbcb1f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("team_member_role_code", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "team_member_role_code")
    # ### end Alembic commands ###
