"""create sequence_linkedin_activities table

Revision ID: dbea80f0229b
Revises: 295f6fd9d018
Create Date: 2025-08-04 03:18:59.594944

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "dbea80f0229b"
down_revision = "295f6fd9d018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequence_linkedin_activities",
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("sequence_campaign_id", sa.Integer(), nullable=True),
        sa.Column("sequence_step_id", sa.Integer(), nullable=True),
        sa.Column("sequence_person_id", sa.Integer(), nullable=True),
        sa.Column("linkedin_account_id", sa.Integer(), nullable=True),
        sa.Column("thread_id", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SENT",
                "FAILED",
                "SKIPPED",
                "SCHEDULED",
                "REPLIED",
                name="linkedinhistorystatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "process_status",
            sa.Enum(
                "PENDING",
                "PERSON_PAUSED",
                "SUCCESS",
                "FAILED",
                name="linkedinhistoryprocessstatus",
            ),
            nullable=True,
        ),
        sa.Column("next_sequence_step_id", sa.Integer(), nullable=True),
        sa.Column("sent_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("sent_by", sa.Integer(), nullable=True),
        sa.Column("replied_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("is_rescheduled", sa.Boolean(), nullable=True),
        sa.Column("tracking_token", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence_linkedin_activities")

    # Xoá kiểu enum nếu tồn tại (chỉ với PostgreSQL)
    op.execute("DROP TYPE IF EXISTS linkedinhistoryprocessstatus")
    op.execute("DROP TYPE IF EXISTS linkedinhistorystatus")

    # ### end Alembic commands ###
