"""empty message

Revision ID: d5dfedd98791
Revises: 2ca7dca3f2e3
Create Date: 2025-06-09 08:34:13.558236

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "d5dfedd98791"
down_revision = "2ca7dca3f2e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    enrichment_status = postgresql.ENUM(
        "BEING_IDENTIFIED", "IDENTIFIED", "FAILED", name="enrichment_status"
    )
    enrichment_status.create(op.get_bind())

    # Then add the column
    op.add_column(
        "enrichments",
        sa.Column(
            "status",
            sa.Enum(
                "BEING_IDENTIFIED", "IDENTIFIED", "FAILED", name="enrichment_status"
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("enrichments", "status")

    # Drop the enum type
    enrichment_status = postgresql.ENUM(
        "BEING_IDENTIFIED", "IDENTIFIED", "FAILED", name="enrichment_status"
    )
    enrichment_status.drop(op.get_bind())
    # ### end Alembic commands ###
