"""after column total companies and error message

Revision ID: 4fd0fb9680d6
Revises: dd0b85a3e80c
Create Date: 2025-08-05 02:34:21.382360

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4fd0fb9680d6"
down_revision = "dd0b85a3e80c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesforce_sync_histories",
        sa.Column("total_companies", sa.Integer(), nullable=True),
    )
    op.add_column(
        "salesforce_sync_histories",
        sa.Column("error_message", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("salesforce_sync_histories", "error_message")
    op.drop_column("salesforce_sync_histories", "total_companies")
    # ### end Alembic commands ###
