"""empty message

Revision ID: 05bc7ff99aa0
Revises: 0c39fc4ef899
Create Date: 2025-02-12 03:59:08.312368

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05bc7ff99aa0'
down_revision = '0c39fc4ef899'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequence_mail_templates', sa.Column('external_mautic_mail_template_id', sa.Integer(), nullable=True))
    op.add_column('sequence_campaign_steps', sa.Column('uuid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequence_mail_templates', 'external_mautic_mail_template_id')
    op.drop_column('sequence_campaign_steps', 'uuid')
    # ### end Alembic commands ###
