"""empty message

Revision ID: c10dbcf419a2
Revises: 40cb739e16d4
Create Date: 2025-04-11 08:51:25.878133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c10dbcf419a2'
down_revision = '40cb739e16d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE subcriptions ALTER COLUMN "
        "plan_code TYPE plancode"
        " USING plan_code::text::plancode"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE subcriptions ALTER COLUMN plan_code "
        "TYPE varchar(20) USING plan_code::varchar"
    )
    # ### end Alembic commands ###
