"""empty message

Revision ID: 628dbb112986
Revises: 81404e8ace8c
Create Date: 2025-06-17 12:24:37.716444

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "628dbb112986"
down_revision = "decb0c741bad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enrichment_item_data",
        "value",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            UPDATE enrichment_item_data
            SET value = LEFT(value, 255)
            WHERE LENGTH(value) > 255
            """
        )
    )
    op.alter_column(
        "enrichment_item_data",
        "value",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
