"""update user table with init team_member_role

Revision ID: f5ac93e3bd40
Revises: 48d40daaffcc
Create Date: 2025-07-15 02:37:09.236587

"""
from alembic import op
from app.models.user import TeamMemberRoleCode

# revision identifiers, used by Alembic.
revision = "f5ac93e3bd40"
down_revision = "48d40daaffcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""
        UPDATE users
        SET team_member_role_code = '{TeamMemberRoleCode.MANAGER}'
        WHERE (team_member_role_code IS NULL AND team_id IS NOT NULL)
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
