"""update mailbox field

Revision ID: 51cae7bb87fa
Revises: 2c1aaaf68087
Create Date: 2025-02-24 10:45:41.003246

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "51cae7bb87fa"
down_revision = "2c1aaaf68087"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mailboxes",
        sa.Column("imap_email", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "sequence_mailboxes",
        sa.Column("imap_password", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "sequence_mailboxes",
        sa.Column("imap_host", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "sequence_mailboxes", sa.Column("imap_port", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mailboxes", "imap_port")
    op.drop_column("sequence_mailboxes", "imap_host")
    op.drop_column("sequence_mailboxes", "imap_password")
    op.drop_column("sequence_mailboxes", "imap_email")
    # ### end Alembic commands ###
