"""add linkedin_accounts table

Revision ID: cf45f4864d01
Revises: 6dd7c5140ae3
Create Date: 2025-07-24 04:17:11.919473

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cf45f4864d01"
down_revision = "6dd7c5140ae3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkedin_accounts",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CREATION_SUCCESS", "CREDENTIALS", name="linkedinaccountstatus"),
            nullable=True,
        ),
        sa.Column("account_id", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkedin_accounts")
    # ### end Alembic commands ###
