"""empty message

Revision ID: 8eae74719cb2
Revises: ba5d157d8247
Create Date: 2025-05-23 07:16:42.800033

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8eae74719cb2"
down_revision = "ba5d157d8247"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE exportstatus
        AS ENUM (
            'IN_PROGRESS', 'AVAILABLE', 'UNAVAILABLE'
        );
    """
    )
    op.add_column(
        "export_histories",
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "AVAILABLE", "UNAVAILABLE", name="exportstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("export_histories", "status")
    # ### end Alembic commands ###
