"""add column is_primary in table mail_aliases

Revision ID: 40cb739e16d4
Revises: 74c7d1b9aa75
Create Date: 2025-04-11 06:40:58.162933

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "40cb739e16d4"
down_revision = "a30bdf1754cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mail_aliases", sa.Column("is_primary", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_aliases", "is_primary")
    # ### end Alembic commands ###
