"""init_mailboxes_table

Revision ID: dcbc990a5308
Revises: f4ce277b95de
Create Date: 2025-02-17 09:03:49.673828

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dcbc990a5308"
down_revision = "f4ce277b95de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sequence_mailboxes",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("host", sa.String(length=128), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("emails_sent_per_day", sa.Integer(), nullable=True),
        sa.Column("emails_sent_per_hour", sa.Integer(), nullable=True),
        sa.Column("delay_between_emails", sa.Integer(), nullable=True),
        sa.Column("email_signature", sa.Text(), nullable=True),
        sa.Column("opt_out_message_after_signature", sa.Text(), nullable=True),
        sa.Column("is_opt_out_message_after_signature", sa.Boolean(), nullable=True),
        sa.Column("is_open_tracking", sa.Boolean(), nullable=True),
        sa.Column("is_click_tracking", sa.Boolean(), nullable=True),
        sa.Column(
            "is_include_one_click_unsubscribe_headers", sa.Boolean(), nullable=True
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence_mailboxes")
    # ### end Alembic commands ###
