"""alter column file_path in sequence_step_content_items table

Revision ID: c627106f135b
Revises: 7a4cfe2632a9
Create Date: 2025-08-18 07:57:08.403250

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c627106f135b"
down_revision = "7a4cfe2632a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_step_content_items",
        "mime_type",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "sequence_step_content_items",
        "file_path",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_step_content_items",
        "file_path",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "sequence_step_content_items",
        "mime_type",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
