"""Create table persons_custom

Revision ID: b5408578df7e
Revises: 8489f9f67031
Create Date: 2025-02-19 07:13:59.893026

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b5408578df7e"
down_revision = "8489f9f67031"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons_custom",
        sa.Column("uuid", sa.String(length=64), nullable=True),
        sa.Column("person_custom_uuid", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("role_name", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("linkedin_url", sa.String(length=1024), nullable=True),
        sa.Column("twitter_url", sa.String(length=1024), nullable=True),
        sa.Column("github_url", sa.String(length=1024), nullable=True),
        sa.Column("note_url", sa.String(length=1024), nullable=True),
        sa.Column("fb_url", sa.String(length=1024), nullable=True),
        sa.Column("wantedly_url", sa.String(length=1024), nullable=True),
        sa.Column("skills", sa.Text(), nullable=True),
        sa.Column("corporate_number", sa.ARRAY(sa.String(length=64)), nullable=True),
        sa.Column("company_name", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("wantedly_id", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("linkedin_internal_id", sa.String(length=255), nullable=True),
        sa.Column("intro", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("role_code", sa.Text(), nullable=True),
        sa.Column("role_group_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person_custom_uuid", name="person_custom_uuid_unique"),
    )
    op.add_column(
        "person_collection_items",
        sa.Column("person_custom_uuid", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person_collection_items", "person_custom_uuid")
    op.drop_table("persons_custom")
    # ### end Alembic commands ###
