"""add column is_default in table sequence_mailboxes

Revision ID: 0688ab7a408a
Revises: c10dbcf419a2
Create Date: 2025-04-14 06:25:51.991130

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0688ab7a408a"
down_revision = "c10dbcf419a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sequence_mailboxes", sa.Column("is_default", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mailboxes", "is_default")
    # ### end Alembic commands ###
