"""after column code in hubspot integrations table

Revision ID: 73970cd5d39f
Revises: f797d5a10614
Create Date: 2025-03-21 03:43:04.621455

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "73970cd5d39f"
down_revision = "f797d5a10614"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hubspot_integrations", sa.Column("code", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hubspot_integrations", "code")
    # ### end Alembic commands ###
