"""empty message

Revision ID: 599eee8b7d2b
Revises: d86a5df98085
Create Date: 2025-03-17 02:47:46.189062

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "599eee8b7d2b"
down_revision = "d45eb291d589"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        CREATE TYPE mailhistoryprocessstatus
        AS ENUM (
            'PENDING',
            'PERSON_PAUSED',
            'MAILBOX_NOT_FOUND',
            'SUCCESS',
            'FAILED'
        );
    """
    )
    op.add_column(
        "sequence_mail_histories",
        sa.Column(
            "process_status",
            sa.Enum(
                "PENDING",
                "PERSON_PAUSED",
                "MAILBOX_NOT_FOUND",
                "SUCCESS",
                "FAILED",
                name="mailhistoryprocessstatus",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_mail_histories", "process_status")
    # ### end Alembic commands ###
