"""create index table error log

Revision ID: 2d040c41be16
Revises: fe9db7ca4f75
Create Date: 2025-05-05 09:30:39.478708

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d040c41be16"
down_revision = "fe9db7ca4f75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_hubspot_company_push_histories_id",
        "hubspot_company_push_histories",
        ["id"],
        unique=False,
    )
    op.create_index(
        "idx_hubspot_pull_person_histories_id",
        "hubspot_pull_person_histories",
        ["id"],
        unique=False,
    )
    op.create_index(
        "idx_salesforce_company_pull_histories_id",
        "salesforce_company_pull_histories",
        ["id"],
        unique=False,
    )
    op.create_index(
        "idx_salesforce_company_push_histories_id",
        "salesforce_company_push_histories",
        ["id"],
        unique=False,
    )
    op.create_index(
        "idx_salesforce_person_pull_histories_id",
        "salesforce_person_pull_histories",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_salesforce_person_pull_histories_id",
        table_name="salesforce_person_pull_histories",
    )
    op.drop_index(
        "idx_salesforce_company_push_histories_id",
        table_name="salesforce_company_push_histories",
    )
    op.drop_index(
        "idx_salesforce_company_pull_histories_id",
        table_name="salesforce_company_pull_histories",
    )
    op.drop_index(
        "idx_hubspot_pull_person_histories_id",
        table_name="hubspot_pull_person_histories",
    )
    op.drop_index(
        "idx_hubspot_company_push_histories_id",
        table_name="hubspot_company_push_histories",
    )
    # ### end Alembic commands ###
