"""add upload_process_status in sequence_campaign_imports table and enrichment_files table

Revision ID: 6dd7c5140ae3
Revises: e8abcb42971a
Create Date: 2025-07-23 09:51:32.945794

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6dd7c5140ae3"
down_revision = "e8abcb42971a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "enrichment_files",
        sa.Column("upload_process_status", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "sequence_campaign_imports",
        sa.Column("upload_process_status", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sequence_campaign_imports", "upload_process_status")
    op.drop_column("enrichment_files", "upload_process_status")
    # ### end Alembic commands ###
