"""after table salesforce_field_mappings_default

Revision ID: c6628f19dec3
Revises: a5c33749c6c1
Create Date: 2025-03-24 09:02:18.191856

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c6628f19dec3"
down_revision = "a5c33749c6c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "salesforce_field_mappings_default",
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("salesmart_field", sa.String(length=255), nullable=True),
        sa.Column("salesforce_field", sa.String(length=255), nullable=True),
        sa.Column("is_over_write", sa.Boolean(), nullable=True),
        sa.Column("is_auto_fill", sa.Boolean(), nullable=True),
        sa.Column("is_suggested_field", sa.Boolean(), nullable=True),
        sa.Column(
            "field_class",
            sa.Enum(
                "PREDEFINED",
                "CUSTOM",
                name="field_class_mapping_enum_default",
            ),
            nullable=True,
        ),
        sa.Column(
            "object_type",
            sa.Enum(
                "PERSONS",
                "COMPANIES",
                name="object_type_enum",
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salesforce_field_mappings_default")
    # ### end Alembic commands ###
