"""add password_updated_at to user table

Revision ID: 53f422ad9e56
Revises: 82e3a4d4e88b
Create Date: 2025-07-09 10:30:20.691430

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "53f422ad9e56"
down_revision = "9b1276e8a7e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_updated_at")
    # ### end Alembic commands ###
