"""change column name salesforce_comapny_id to salesforce_company_id

Revision ID: 02e0b2bd2d8c
Revises: e1e84711792c
Create Date: 2025-05-19 09:40:53.643353

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "02e0b2bd2d8c"
down_revision = "e1e84711792c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesforce_raw_companies",
        sa.Column("salesforce_company_id", sa.String(length=255), nullable=True),
    )
    op.drop_constraint(
        "salesforce_raw_companies_unique_key",
        "salesforce_raw_companies",
        type_="unique",
    )
    op.create_unique_constraint(
        "salesforce_raw_companies_unique_key",
        "salesforce_raw_companies",
        ["salesforce_team_id", "salesforce_integration_id", "salesforce_company_id"],
    )
    op.drop_column("salesforce_raw_companies", "salesforce_comapny_id")
    op.add_column(
        "salesforce_synced_companies",
        sa.Column("salesforce_company_id", sa.String(length=255), nullable=True),
    )
    op.drop_column("salesforce_synced_companies", "salesforce_comapny_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "salesforce_synced_companies",
        sa.Column(
            "salesforce_comapny_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("salesforce_synced_companies", "salesforce_company_id")
    op.add_column(
        "salesforce_raw_companies",
        sa.Column(
            "salesforce_comapny_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        "salesforce_raw_companies_unique_key",
        "salesforce_raw_companies",
        type_="unique",
    )
    op.create_unique_constraint(
        "salesforce_raw_companies_unique_key",
        "salesforce_raw_companies",
        ["salesforce_team_id", "salesforce_integration_id", "salesforce_comapny_id"],
    )
    op.drop_column("salesforce_raw_companies", "salesforce_company_id")
    # ### end Alembic commands ###
