"""after column is_suggested_field in field mapping table

Revision ID: 0a9cc2d1e992
Revises: ac0a828ad0f6
Create Date: 2025-02-25 02:30:20.279087

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0a9cc2d1e992"
down_revision = "ac0a828ad0f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field_mapping_hubspot",
        sa.Column("is_suggested_field", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_mapping_hubspot", "is_suggested_field")
    # ### end Alembic commands ###
